### ISSUE TITLE
some tweaks

### ISSUE THREAD

**Issue by rezad1393** [Purfview/IMDb-Scout-Mod#1]
can you change to  these?

      torrentgalaxy.to to  torrentgalaxy.mx because on its website it say:
"torrentgalaxy.to is about to be blocked in several regions.     Stay with us! Bookmark https://proxygalaxy.pw to keep our official proxy list."
        also use it for tv too?

http**s**://search.rlsbb.ru
http**s**://search.proxybb.com
https://limetorrents.unblockit.lat/search/movies/%search_string**_orig**%+%year%/
https://nnm-club.me/forum/tracker.php?nm=%search_string**_orig**%

can you generally change the search_string to search_string_orig ?

also a tip.
if you use firefox you can use httpz addon to be sure to get all the websites that support https over https.

**Comment by Purfview** [comment]
TGx updated, and tv search added.
RlsBB doesn't work with SSL.
NNM updated, split, and changed to %search_string_orig%.
I don't see benefit of changing it for LimeTor, and there is no benefit in general if sites doesn't prefer original titles.
