### ISSUE TITLE
New added links in icons section doesn't appear

### ISSUE THREAD

**Issue by mastercho** [Purfview/IMDb-Scout-Mod#101]
I did add few other google dorks after google under icons section but seems they are available to choose in settings.

I did add these after google, but only Google is available to select, would like to know the reason. Thanks!

```
 {   'name': 'Google',
      'searchUrl': 'https://www.google.com/search?q=%search_string%'},
  {   'name': 'Google Subs',
      'searchUrl': 'https://www.google.com/search?q=%search_string%+%year%+subtitles'},
  {   'name': 'Google Tr Dublaj',
      'searchUrl': 'https://www.google.com/search?q=%search_string%+%year%+Türkçe+Dublaj'},
```

**Comment by Purfview** [comment]
I pasted in your sites and they work OK for me.

Maybe you added 'Google' twice?

**Comment by mastercho** [comment]
They are added just as i post above after google 2 more lines and they are not appearing on my side, tried on 4 different computers all same, maybe you still didn't commit anything that its fixes the issue

**Comment by Purfview** [comment]
There is no issue with your example. Share your whole script.

**Comment by mastercho** [comment]
https://github.com/mastercho/IMDb-Scout-Mod/blob/dev/IMDb_Scout_Mod.user.js also IMDB updated again and script stoped working from today :/

**Comment by Purfview** [comment]
> https://github.com/mastercho/IMDb-Scout-Mod/blob/dev/IMDb_Scout_Mod.user.js 

And why you don't PR sites? Now for me it looks like a huge mess... good luck deciphering it now. 
Custom sites should be added to `var custom_sites` to keep things in order.


> also IMDB updated again and script stoped working from today :/

You can use the reference view where they don't do layout experiments. It's much better than that nonsense redesigned layout.
Enable in settings: "Enable Reference View: Force it".

Tested that redesigned layout:  On Opera it works, on Waterfox it doesn't load at all. What browser do you use?
If it will not fix by itself next week then let me know.

**Comment by mastercho** [comment]
> also IMDB updated again and script stopped working from today :/

That was TemperMonkey issue, after restart of browser got updated and was fixed. 

I do some customizations on it that's why i don't do PR and too lazy to separate with sites like i did in my dev branch now... Anyway you just need google part and you can see they are in order in icon _sites

**Comment by Purfview** [comment]
> 
> That was TemperMonkey issue, after restart of browser got updated and was fixed.

It can't magically break by itself.
Works for me too now, told you that IMDb does experiments on that layout [every day].

> I do some customizations on it that's why i don't do PR

That is exactly what GitHub is about, and PR is just few clicks.

> Anyway you just need google part and you can see they are in order in icon _sites

Already told you that "google part" works [OK](https://github.com/Purfview/IMDb-Scout-Mod/issues/101#issuecomment-1103439568). Rest is a crazy mess for you to decipher.
You are lazy to press PR button and you expect me to look at 478 differences... ;)
