### ISSUE TITLE
"More like this" section seems to disappear

### ISSUE THREAD

**Issue by iivmok** [Purfview/IMDb-Scout-Mod#103]
On the 17.0.1 version of this script with all other plugins disabled the "More like this" section on an imdb page for a movie disappears after the loader. For ex. here: https://www.imdb.com/title/tt0076759/

With script enabled:

![image](https://user-images.githubusercontent.com/5609872/167250166-bff5a5a9-e40f-4793-b1e6-0907ddc138c5.png)

With script disabled:

![image](https://user-images.githubusercontent.com/5609872/167250205-1b9c1d98-fb34-4355-99b5-ab966ca2fa13.png)

**Comment by Purfview** [comment]
Thanks for report, I'll check it this weekend.  
Meanwhile you can try to disable ads removal setting, I suspect that it's the culprit.

**Comment by Purfview** [comment]
Sorry for late check.
All good on my side, "More like this" section doesn't disappear.
Maybe it was one of those IMDb's new-design experiments.
