### ISSUE TITLE
Refused to connect to... URL was permanently blocked by the user

### ISSUE THREAD

**Issue by Iceboy-6** [Purfview/IMDb-Scout-Mod#106]
Hello!
As you can see in the screenshot below, i am not able to see the ratings of Rotten Tomatoes and Letterboxd in IMDb pages.

![image](https://user-images.githubusercontent.com/78272358/169700307-a7272679-286b-4688-9235-68b67717773e.png)

Sites:
IMDb https://www.imdb.com/title/tt0068646/
RT https://www.rottentomatoes.com/search?search=The%20Godfather
Letterboxd https://letterboxd.com/film/the-godfather/

Versions:
Google Chrome 101.0.4951.67 64 bits
Tampermonkey 4.16.1
All adblockers and other scripts are deactivated in IMDb site.

Console:
![image](https://user-images.githubusercontent.com/78272358/169700827-b77f0a74-f65f-451b-bf4b-0c6248108a01.png)
![image](https://user-images.githubusercontent.com/78272358/169700835-f604c9b7-43ba-4e07-a2ca-fb799abd9fd0.png)
![image](https://user-images.githubusercontent.com/78272358/169700841-37cca735-37f0-4b8a-83ec-f4fe3fb07683.png)

**VM590:26 Refused to connect to "https://letterboxd.com/imdb/0068646": URL was permanently blocked by the user
(anônimo) @ VM590:26
VM590:26 Refused to connect to "http://www.omdbapi.com/?i=tt0068646&apikey=3fdb9c5a&plot=full&tomatoes=true": URL was permanently blocked by the user**

I don't know why the connections are been refused. When I click in the links, I am able to connect.

Thank you.

**Comment by Purfview** [comment]
I tested your link all ratings work there [on Waterfox].

Did it worked for you before?

**Comment by Purfview** [comment]
Before "Refused to connect to" there is triangle, try to press it for more info.
Maybe you are blocking connections with Tampermonkey's settings.
Try another script manager like Violentmonkey.

**Comment by Iceboy-6** [comment]
I added an asterisk * in the user domain whitelist as instructed and now all ratings are working.

Thank you for your help.

Here are the screenshots in case other users eventually have this problem in the future.

![image](https://user-images.githubusercontent.com/78272358/169782487-13b839e6-cf56-42a8-8cad-1f9b30a7a4e4.png)
![image](https://user-images.githubusercontent.com/78272358/169782554-46a6d76b-aede-4583-83c6-c8f7dc4b815d.png)
