### ISSUE TITLE
error in pornolab search

### ISSUE THREAD

**Issue by rezad1393** [Purfview/IMDb-Scout-Mod#115]
this 
https://pornolab.net/forum/search.php?po=1&dm=1&nm=$tt-id
gives this error
`Could not connect to the server `

**Comment by Purfview** [comment]
Removed it - https://github.com/Purfview/IMDb-Scout-Mod/commit/18fb167cab239922e8584507da9e53cf5670af9a
Thanks for report.

**Comment by Purfview** [comment]
I dunno, when did it stopped working? Maybe it's temporary problem...

**Comment by rezad1393** [comment]
for two weeks I think.

**Comment by Purfview** [comment]
It started to work again. :)
https://pornolab.net/forum/search.php?po=1&dm=1&nm=tt0071464
