### ISSUE TITLE
disable notification for IMDb-Scout-Mod in the settings

### ISSUE THREAD

**Issue by nzarbayezid** [Purfview/IMDb-Scout-Mod#117]
I'm not always running Ridarr and Sonarr, and by visiting the IMDb website and watching a move profile, it always gives me an annoying [notification](https://imgur.com/a/omuPwxA), so either I have to open Ridarr and Sonarr all the time or I have to disable the Ridarr and Sonarr in IMDb-Scout-Mod. so please add a future to give us an option to disable or enable the notification of the script for an error,
thanks for your best IMDb script ever.

https://imgur.com/a/omuPwxA

**Comment by Purfview** [comment]
Isn't easier just to disable notifications in your browser?
At the left from the url field there is a padlock, when pressed there is option to disable notifications on site. [Opera and Waterfox]

**Comment by nzarbayezid** [comment]
> At the left from the url field there is a padlock, when pressed there is option to disable notifications on site. 
I have always disabled all site notifications for google, even with that it's the same thing


https://user-images.githubusercontent.com/101425664/174418415-36d4ea99-7348-4544-bb75-474db3a59d3e.mp4

**Comment by nzarbayezid** [comment]
there is only one way I have to disable the notification for google chrome which is something I cant do because there is a lot of other extensions that i risive important notifications from

**Comment by Purfview** [comment]
I guess I can add option to disable them,  but only those about radarr/sonarr not running.

**Comment by nzarbayezid** [comment]
that' a good idea, cuz I tried even with tempermonky to disable notification form it but even there was no option from there, so it gotta be added, thanks

**Comment by nzarbayezid** [comment]
![image](https://user-images.githubusercontent.com/101425664/174548454-79e6d6f1-3457-4720-80dd-3073c5457c9c.png)

**Comment by Purfview** [comment]
Added option to disable it in v17.3 [at the bottom of Title Page section].
