### ISSUE TITLE
Bugged Douban and Metacritic ratings on the mobile browsers

### ISSUE THREAD

**Issue by nzarbayezid** [Purfview/IMDb-Scout-Mod#118]
I don't know if you are focusing on Firefox nightly in any way, I saw that you said you (Support mobile: [Firefox Nightly) and I gave it a try and it really doing good for my needs I'm happy with it. but I notice that the Douban ratings are not showing but if you press the Douban icon it will direct you to the Douban website correctly.

https://user-images.githubusercontent.com/101425664/174410932-e3441679-b3f8-4269-8dba-4d47e0b86569.mp4

**Comment by Purfview** [comment]
Hmm, interesting why it's bugged, all ratings run similar code. Btw, Metacritic is bugged out too.

Probably will be hard to debug this...

**Comment by Purfview** [comment]
Fixed in v17.10
