### ISSUE TITLE
Average all ratings into a one rating

### ISSUE THREAD

**Issue by nzarbayezid** [Purfview/IMDb-Scout-Mod#119]
What I love about this script is that it will show me all the ratings of the movie and based on that I know if a movie is worth watching.

![image](https://user-images.githubusercontent.com/101425664/174414494-56b71981-f6f6-4fe0-8e5f-28f11c0f7e2a.png)

but there is a good idea around that, we can create an overall score base on all the ratings on the screen, that way we know what's the overall ratings of the movie based on all the top rating sites.
I have created a design to demonstrate the idea 👇👇👇

![Screenshot 2022-06-18 021327](https://user-images.githubusercontent.com/101425664/174414775-db23a7d9-f534-49ed-b84a-b7e7ca2a9b4f.jpg)

what's good about this future is that some moves have different opinions from critics and the audience, so that way based on all that ratings from all the sites and both critics and audience you get an idea what's the overall rating of the movies, sounds good?

for that of course we can use this design 👇👇👇
 
![Group 1](https://user-images.githubusercontent.com/101425664/174415026-3493b4f6-47f2-4229-b595-8343e3804d93.png) ![Group 12](https://user-images.githubusercontent.com/101425664/174416074-b8df478b-17f2-4ec9-9991-3a79c84b05df.png)

or these 👇👇👇

![image](https://user-images.githubusercontent.com/101425664/174415062-ca5f5122-c2f6-4a2d-b66b-2e1aa391fe52.png)
![image](https://user-images.githubusercontent.com/101425664/174415074-b3e2c6a7-b9cb-4c39-ac67-231203fbe524.png)
![image](https://user-images.githubusercontent.com/101425664/174415083-cce63126-b05b-4697-aa79-07cbee5ea60d.png)

You get the idea now, I don't know about codding but I don't think that's something that we can't achieve cuz all you gotta do is take all the ratings and addition them (+) then divided them by how many ratings we have currently on the screen, that all, like this

![image](https://user-images.githubusercontent.com/101425664/174415628-73ae2bda-1b12-496c-8a53-42431e6ffefb.png)

I can help you out by designing the icons for you cuz I really love your script and not that I want it to be contained also I wanna make it better.

**Comment by Purfview** [comment]
You can't average different things and get the meaningful results, all those scores are incomparable.
More over, **raw averaging** by it self doesn't carry much meaning as it **doesn't represent what you think it represents.**

In short: Such average is meaningless = a pointless number.
