### ISSUE TITLE
Add Simkl using it's redirect API

### ISSUE THREAD

**Issue by masyk** [Purfview/IMDb-Scout-Mod#127]
Service: Simkl (https://simkl.com)
Icon: https://us.simkl.in/img_favicon/v2/favicon-32x32.png

Redirect API: https://simkl.docs.apiary.io/#reference/redirect/redirect-to-simkl-trailer-or-twitter/redirect (can use IMDB ID)

**Comment by Purfview** [comment]
Simkl is already added at the icon sites.
URL example: https://simkl.com/search/?q=tt0088247
