### ISSUE TITLE
Page seems broken for TorrentDB results

### ISSUE THREAD

**Issue by su1na** [Purfview/IMDb-Scout-Mod#128]
When trying to obtain a filtered page for the tracker TorrentDB, the resulting page seems to be formatted incorrectly [like so](https://i.imgur.com/N1ArZH2.png).

The sysop has mentioned that they had a major website revamp recently which may have broken the script.

**Comment by Purfview** [comment]
There's nothing I can do about it, only a sysop of that site can fix it.
Other UNIT3D sites works OK, so something was broken when the site was customized.

**Comment by Purfview** [comment]
Closing as issue is not related to the script.
