### ISSUE TITLE
"Limit reached!"  Set OMDB API key in settings....

### ISSUE THREAD

**Issue by p3ngwin** [Purfview/IMDb-Scout-Mod#132]
Keep getting this message:
""Limit reached!"  Set OMDB API key in settings...."

 i have an OMDB API key, but going to the script's "settings" page shows nowhere to use the API key ??  

Even on the Script's main Github page there's no reference at all to "OMDB" let alone the "OMFB API" key ??  

Am i missing something, or is there no way to enter the API KEY ?

**Comment by arogl** [comment]
Look here

![image](https://user-images.githubusercontent.com/1115472/192220677-40689d22-e79a-4c0b-a522-c2866587d096.png)

**Comment by p3ngwin** [comment]
Hmmm, i've looked on OMDB's page for "how to use" but i still can't get it to work :(  

On their page it says to use :  

**http://www.omdbapi.com/?apikey=[yourkey]&**  

but regardless if i put my key with, or without, the brackets, still no joy :(  

i've tried just the number on it's own, still nothing.  

Thanks for the swift reply, and i hope it's something simple that is either not communicated well somewhere, or i'm an idiot and missed it completely :)

**Comment by Purfview** [comment]
> Hmmm, i've looked on OMDB's page for "how to use" but i still can't get it to work :(
> 

Paste your Key there in to the settings.

**Comment by p3ngwin** [comment]
So is the "key" the whole **http://www.omdbapi.com/?apikey=[yourkey]&** as shown on OMDB's website, or is it literally just the 8 digit number ?

**Comment by arogl** [comment]
8 digit code pasted into the box above and then hit save.

**Comment by p3ngwin** [comment]
awesome, thanks, i'll do that, and wait a few days to see if it works, cheers :)
