### ISSUE TITLE
Tracker Crna Berza support request

### ISSUE THREAD

**Issue by Marcus051333** [Purfview/IMDb-Scout-Mod#145]
Tracker name: Crna Berza
URL: www.crnaberza.com

**Comment by Purfview** [comment]
That site needs invite.

**Comment by Marcus051333** [comment]
Unfortunately not.

**Comment by Purfview** [comment]
Then contact me at purfview [@] protonmail.com

**Comment by Purfview** [comment]
Added to v18.2.
