### ISSUE TITLE
No JSON in response for Sonarr v4 beta

### ISSUE THREAD

**Issue by azuravian** [Purfview/IMDb-Scout-Mod#147]
I am getting No JSON in response for Sonarr.  Radarr is working fine.

Radarr is version 4.3.2.6857
Sonarr is version 4.0.0.373

I'm guessing this is due to me using Sonarr v4, which is still in development.  Is there any possibility of supporting this, or allowing me to disable that error notification?

**Comment by Purfview** [comment]
Is new API backwards compatible? If not then I will look at it only after stable v4 release.

**Comment by azuravian** [comment]
It appears that all API calls still reference v3, but I'm not sure of any changes that may have been made along the way.

**Comment by Purfview** [comment]
Added support for Sonarr-v4 in v19.5.
