### ISSUE TITLE
Rotten Tomatoes ratings doesn't work for episodes of TV series

### ISSUE THREAD

**Issue by harrytyp** [Purfview/IMDb-Scout-Mod#148]
The automated Rotten Tomatoes score viewer does not work currently, as the link it fetches adds an additional 'season' marker for TV series. It however works just fine for movies.

e.g. the script fetches

https://www.rottentomatoes.com/tv/the_last_of_us/s01/e06/s01

which should be 

https://www.rottentomatoes.com/tv/the_last_of_us/s01/e06/

I am unsure where the issue is created.

Thanks for your great work! 👍

**Comment by Purfview** [comment]
It's fixed: https://www.imdb.com/title/tt14659496
