### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by edge20200** [Purfview/IMDb-Scout-Mod#151]
https://i.imgur.com/95eDFDn.png

IMDB now showing this with IMDB scout, different browsers and resetting to default does not fix.

**Comment by Rediscovered3030** [comment]
Experiencing the same issue, all blurred, I do notice movement behind the blur which suggests there is some sort of loading going on, just cannot see or interact with anything.

**Comment by Purfview** [comment]
Still OK here, need to wait till this "feature" comes here too.

Meanwhile you can enable "Reference View: Force it (without login)" option in the settings.

**Comment by mastercho** [comment]
Same here, seems IMDB keeps eye on this script

**Comment by Purfview** [comment]
> Same here, seems IMDB keeps eye on this script

Yeah, this blurring looks pretty weird.

**Comment by Rediscovered3030** [comment]
I am not getting it anymore.

**Comment by Rediscovered3030** [comment]
> Same here, seems IMDB keeps eye on this script

That is what it looked like to me.
Naughty IMDb, just let us do our thing.

**Comment by Purfview** [comment]
Nah, they have a saboteur from TMDb, he is working hard to move people away from IMDb. :D

**Comment by mastercho** [comment]
> I am not getting it anymore.

hm 6 hours later im still getting it

**Comment by Purfview** [comment]
> hm 6 hours later im still getting it

Still OK here... I've feeling that this "feature" doesn't work on Windows 7...
In "test" branch I committed a fix, please test if it fixes anything.

**Comment by Purfview** [comment]
Should be fixed in [v19.0](https://github.com/Purfview/IMDb-Scout-Mod/commit/a860a63486e760be94c64515d6589a0567a9143c).

**Comment by mastercho** [comment]
Seems fails to get movie title in 19.0 into %search_string%
