### ISSUE TITLE
Title and Original title are not picked up

### ISSUE THREAD

**Issue by jijoooo** [Purfview/IMDb-Scout-Mod#153]
For example YouTube link it generates:
https://www.youtube.com/results?search_query=%22%22+2023+trailer

This link is for The Last of Us (2023), but same thing happens with other titles...

**Comment by Purfview** [comment]
Will be fixed v19.1, if you are in a hurry then it's fixed in the "test" and "test2" branches.

**Comment by Mister-Book** [comment]
Thanks!!!!

**Comment by Mister-Book** [comment]
I feel like an addict, Scout Mod does so much for me, and it is hard to remember how things were before I had it only a few months ago.  Thanks for the latest fix (pun intended)

**Comment by Mister-Book** [comment]
I just loaded test 2, and it isn't working for Ok.Ru , youtube, Tubi or Ulozto, I'm not sure how many others

**Comment by Purfview** [comment]
> I just loaded test 2, and it isn't working for Ok.Ru , youtube, Tubi or Ulozto, I'm not sure how many others

Are you able to see this new imdb's colorful background without the script?
Like here:: https://ptpimg.me/l9lb9h.png

If you can then check if you can see same effect with the "test3" script ON.

**Comment by Mister-Book** [comment]
I just loaded test 3.  I can't see the background and the search for OK.Ru isn't working (only one I checked).  Getting sort of a big grey block which actually covers part of the photos from the movie which are part of the regular page!

**Comment by Purfview** [comment]
Dunno what that means, make a screenshot.

**Comment by Mister-Book** [comment]
![image](https://user-images.githubusercontent.com/126667799/222303073-48b05d7a-cda8-447f-9d86-f891f34c17d2.png)

**Comment by Mister-Book** [comment]
Strange.  That doesn't look like what I'm seeing

**Comment by Mister-Book** [comment]
![image](https://user-images.githubusercontent.com/126667799/222303688-c95d00c2-eb87-49b1-a140-0264f4fe0459.png)

**Comment by Mister-Book** [comment]
every time I try to copy the grey block -- which stuck out beneath the black background field and covered part of the photos, it disappears after I cut and paste it!  Sorry

**Comment by Purfview** [comment]
Strange, are you sure it's script from "test3"? How did you installed it?
For me it looks like  v19.0 from master.

**Comment by Purfview** [comment]
And what "OK.Ru isn't working" means?

**Comment by Purfview** [comment]
Here is the link to test3 branch -> https://github.com/Purfview/IMDb-Scout-Mod/raw/test3/IMDb_Scout_Mod.user.js

**Comment by Mister-Book** [comment]
that link keeps taking me to 19.0

**Comment by Mister-Book** [comment]
no change after I loaded that.  and I still have it searching for the year and not the name

**Comment by Mister-Book** [comment]
I checked force reference view and the search link to Ok.ru is now working, and found the movie I was looking for.  it isn't working without reference view

**Comment by Purfview** [comment]
@Mister-Book 
Fixed in 19.1, open a new issue if still something wrong.
