### ISSUE TITLE
Please add Easynews search 

### ISSUE THREAD

**Issue by coolsudheera** [Purfview/IMDb-Scout-Mod#166]
Excellent script!
Could you please add Easynews search as well?
https://members.easynews.com/2.0/

**Comment by Purfview** [comment]
This looks like a paid service, could you provide your login details?

**Comment by coolsudheera** [comment]
First I want to thank you for this awesome masterpiece userscript!https://signup.easynews.com/july-4th-exclusive-special-2020It's 35 Euros per year for unlimited Usenet access. Easynews is a US based Omicron Usenet server. No need of indexers or nzb downloading software to use this. Simple web search is enough to download or stream anything. Ofcourse any indexer and SABNZBD can be used too. Search url:https://members.easynews.com/2.0/I am extremely sorry my login details cannot be shared! There is a fair use policy in usenet. Hope you would understand!Sent from my Galaxy

**Comment by Purfview** [comment]
Other option is a remote access through TeamViewer or AnyDesk.
Send me email to purfview at protonmail.com if you want this site to be added.
