### ISSUE TITLE
External Ratings Additions - MAL + AniList

### ISSUE THREAD

**Issue by ekk88d** [Purfview/IMDb-Scout-Mod#172]
Hi, could you please look into including External Ratings options from MyAnimeList.com and AniList.co?
They should both be easy to scrape and translate into a xx/100 rating.  Those two resources could be listed last, so ordinary TV and Movies just gray them out, when enabled.

Many media utilities link to IMDB pages, but few directly incorporate ratings for Anime. This'd solve that shortcoming.

Thanks for your ongoing work on this userscript

**Comment by Purfview** [comment]
How you know where from to take those ratings when you can't search those sites by IMDb ID?

**Comment by Purfview** [comment]
It's not limited to IDs, but there is no point in using a wonky search by the titles.
Convert to what IDs?

Btw, IMDb has ratings for anime too.

**Comment by Purfview** [comment]
No need to "reverse engineer" anything, that script just gets IDs from wikidata, IMDb Scout already has similar code.
Anyway, usefulness of those ratings eludes me, can you show me few examples where IMDb "ratings are inconsistent"?

> FYI, many MyAnimeList users are migrating to AniList, so that resource is the priority.

Why they migrate? MAL looks like much more popular site.

**Comment by Purfview** [comment]
Both added in v19.4:

![alt text](https://i.imgur.com/R3iFvrN.png)
