### ISSUE TITLE
torrentgalaxy issue with false positives

### ISSUE THREAD

**Issue by rezad1393** [Purfview/IMDb-Scout-Mod#178]
sometimes torrentgalaxy give a list of torrents found with no items.
like this:
[TGx_Browse Torrents (6_18_2023 9_11_02 PM).zip](https://github.com/Purfview/IMDb-Scout-Mod/files/11782251/TGx_Browse.Torrents.6_18_2023.9_11_02.PM.zip)

can you change torrentgalaxy search be moved to positive search?
when correct torrent are found it is like this in the table 
<div class="tgxtablerow txlight" onmouseover="

I dont know how to add this to the script.

can you also ass a guide for users to add these themselves to the custom part of script?
maybe 3 or 4 example with div detection? right now when I add `<div class="tgxtablerow txlight"` i doesnt work.

**Comment by Purfview** [comment]
No sure what you meant, show me a link where it doesn't work.

**Comment by rezad1393** [comment]
I added this to my own custom part of script and it works.
```
 'positiveMatch': true,
    'matchRegex': /tgxtablerow txlight/,
```

check to see if it is correct and add it?

**Comment by Purfview** [comment]
Should be fixed - https://github.com/Purfview/IMDb-Scout-Mod/commit/46ce91a7d43f2be7752a5e583a213b5768df9df8
