### ISSUE TITLE
Doesn't run in FireMonkey

### ISSUE THREAD

**Issue by dtrauma** [Purfview/IMDb-Scout-Mod#180]
Heya, this extension doesn't run in Firemonkey because of this:

https://github.com/sizzlemctwizzle/GM_config/issues/113

Detailed explanation here:

https://github.com/sizzlemctwizzle/GM_config/wiki/Asynchronous-read-and-write-migration

This also (subtly) affects Greasemonkey 4 users.

**Comment by Purfview** [comment]
> This also (subtly) affects Greasemonkey 4 users.

What is that subtle affect?

**Comment by Purfview** [comment]
To make it work in FireMonkey:
Go to FireMonkey options > select the script > in Options press "Use Wrap code in IIFE" > press Save

PS:
Noticed some bug changing imdb's icon to some icons from the script.

**Comment by dtrauma** [comment]
Indeed, this works, thank you. And sorry if my report was misleading, I was guided by the error message and only now realized that I didn't include it in the report.

**Comment by NLZ** [comment]
> To make it work in FireMonkey: Go to FireMonkey options > select the script > in Options press "Wrap code in IIFE" > press Save

Would it be possible to make it by default?
Or would it cause problems with other userscript managers?

**Comment by Purfview** [comment]
> Would it be possible to make it by default? Or would it cause problems with other userscript managers?

Ask at FireMonkey because all other managers does that automatically.
