### ISSUE TITLE
Request Add New Site

### ISSUE THREAD

**Issue by YagneshDave** [Purfview/IMDb-Scout-Mod#181]
hi can you please add support for this site ?
https://torrentgalaxy.to/
https://torrentgalaxy.to/torrents.php?search=

**Comment by Purfview** [comment]
It's there already -> [L1820](https://github.com/Purfview/IMDb-Scout-Mod/blob/2ce6f73258d53b25c89d932052f2b5334d3f535f/IMDb_Scout_Mod.user.js#L1820)
