### ISSUE TITLE
How can I get the old IMDb layout?

### ISSUE THREAD

**Issue by nzarbayezid** [Purfview/IMDb-Scout-Mod#195]
Maybe this is a silly question I'm sorry about it. could you guys tell me how can I get this [layout](https://imgur.com/a/43EVJCG)? is it an script or this is a setting in IMDB site?

![image](https://github.com/Purfview/IMDb-Scout-Mod/assets/101425664/2a2b7553-e00d-4cdc-adb8-0709acaab56c)

**Comment by Purfview** [comment]
It can be set in your IMDb's acc.
Or in the scripts settings, it's named similar to this - > "Force Reference View without login?"
