### ISSUE TITLE
Enable the 3rd search bar didn't work

### ISSUE THREAD

**Issue by stefionesco** [Purfview/IMDb-Scout-Mod#199]
In Search/List/Watchlist page "Enable the 3rd search bar" didn't work, regardless of whether I select or not the check box.
The same setting in Title Page works perfect.
Here is the screenshots:

![1](https://github.com/Purfview/IMDb-Scout-Mod/assets/155031960/84fc2aaf-caac-4bc3-ba6e-f34646ddb100)
![2](https://github.com/Purfview/IMDb-Scout-Mod/assets/155031960/cbd4bc2d-e655-414a-a67e-e8623d04974f)
![3](https://github.com/Purfview/IMDb-Scout-Mod/assets/155031960/ce4aa95c-4303-49f2-acaf-c1e102285eed)

Thanks in advance.

Stef Ionesco

**Comment by Purfview** [comment]
But those sites are from 2nd bar, you need to select sites from 3rd bar.

**Comment by stefionesco** [comment]
The upper six sites in the second image are from the second bar.
But the  two sites from the third image are from the third bar. In the title page appear on the third bar, but in the list don't.

**Comment by Purfview** [comment]
> The upper six sites in the second image are from the second bar.
> But the two sites from the third image are from the third bar. In the title page appear on the third bar, but in the list don't.

No! The upper six sites are from 1st, and other two are from 2nd bar.

**Comment by stefionesco** [comment]
You are right. Subtitles are from the second. But how come I can't load the second bar in the list?

**Comment by stefionesco** [comment]
Pfff... lol... I have three days trying to do this.
Anyway, it could be nice to have the second bar in the Search/List/Watchlist Page. Maybe it will be added in the future.
Thanks for your time. Very kind of you.

**Comment by Purfview** [comment]
> Anyway, it could be nice to have the second bar in the Search/List/Watchlist Page. Maybe it will be added in the future.

I'll check it, maybe it's not hard to implement it.

**Comment by Purfview** [comment]
Added support for 2nd search bar in v20.0.

Btw, most sites are not checked for its rate limit, if they hit then can show wrong results, you can report it if encounter such.
And I noticed that IMDb redesigned its Advanced search page, script doesn't work there at the moment.

**Comment by stefionesco** [comment]
Thanks for 2nd search bar. It's great.

Happy New year.
