### ISSUE TITLE
new imdb layout?

### ISSUE THREAD

**Issue by rezad1393** [Purfview/IMDb-Scout-Mod#2]
it seems imdb is changing imdb layout and the script doesn't show in that.

**Comment by Purfview** [comment]
It's still in the beta, when it will be final and live then I look into it.

Btw, it look ugly, no idea why they force mobile looks to the desktop users -> https://www.imdb.com/preferences/beta-control?u=/title/tt6450804&e=tmd&t=in

**Comment by rezad1393** [comment]
yes but....
"For a limited time, go back to the older version of this page."
this is gonna change soon.

**Comment by rezad1393** [comment]
I seem to be getting the new layout with no back to legacy like before.
only making firefox forget about imdb seems to restore old interface and that just helps for some time and then I randomly get the new layout and get stuck there.

**Comment by Purfview** [comment]
For me it's in old layout and there is no "go to new beta layout" button anymore. How I should add this new layout, huh... :D

Will check other browsers.

**Comment by rezad1393** [comment]
I understand
it seems to be one of those random A/B tryout that they test on select users randomly.

**Comment by mastercho** [comment]
I did install https://chrome.google.com/webstore/detail/user-agent-switcher/dbclpoekepcmadpkeaelmhiheolhjflj select Firefox useragent clear cookies refresh page and boom old view again

**Comment by Purfview** [comment]
New layout support added to v10.

**Comment by rezad1393** [comment]
thanks.
but I dont think it is just useragent .
I mainly use firefox and I still got it randomly and removing the site data for imdb reverted back to old design but only for some time.
I removed it again and now I am still on old design.
so they are probably testing to roll it out. and the rollout I saw didnt have a go back to old design button.

**Comment by Purfview** [comment]
For me same, it randomly switched to new layout, removing imdb cookies reverts it back. Yesterday they announced:

> Please note, we are gradually launching the new design to a selection of IMDb customers. If you do not yet see the design, we expect to make it broadly available in the weeks ahead. 

With new layout I see issue that it at some 'random' time does soft refresh and custom added elements disappear from the page, now IMDB Scout loads later to avoid that, but sometimes it still reflows page after IMDB Scout is loaded. If someone can indicate what does that, then maybe I can kill it before it runs.

Btw, there is clean reference view, you can enable it at:
https://www.imdb.com/preferences/general

**Comment by rezad1393** [comment]
> For me same, it randomly switched to new layout, removing imdb cookies reverts it back. Yesterday they announced:
> 
> > Please note, we are gradually launching the new design to a selection of IMDb customers. If you do not yet see the design, we expect to make it broadly available in the weeks ahead.
> 
> With new layout I see issue that it at some 'random' time does soft refresh and custom added elements disappear from the page, now IMDB Scout loads later to avoid that, but sometimes it still reflows page after IMDB Scout is loaded. If someone can indicate what does that, then maybe I can kill it before it runs.
> 
> Btw, there is a clean reference view, you can enable it at:
> https://www.imdb.com/preferences/general

thanks for all the replies.
but I did say that from start (though I didnt read that announcement ,too lazy to read) 

also I use addons that remove cookies for websites that I dont care to track me and imdb is one of them.
I for sure would not create and login to it. just a personal thing. so that tip doesnt apply to me.

btw the change in interface uses dark theme in most elemets (for you too?) so I can no longer read the search result from script.
 like so::

![screen](https://user-images.githubusercontent.com/7523164/119119231-40a28c80-ba40-11eb-8213-f85402422a52.png)

**Comment by Purfview** [comment]
Maybe it's possible to force a reference view from script, those links look like this: https://www.imdb.com/title/tt0088247/reference .

Yeap, text mode looks ugly for me too, as I personally don't use text mode then I dunno when I'll look into it, feel free to submit PR.
I guess you would need to edit `p` element at `function getLinkArea()`.

**Comment by rezad1393** [comment]
> Maybe it's possible to force a reference view from script, those links look like this: https://www.imdb.com/title/tt0088247/reference .
> 
> Yeap, text mode looks ugly for me too, as I personally don't use text mode then I dunno when I'll look into it, feel free to submit PR.
> I guess you would need to edit `p` element at `function getLinkArea()`.

I dont thank that is a good solution for me :)
it also changes the tile to a local one but in English words (like instead of terminator it says  'naboodgar') which is pinglish (an ugly hack between english and persian)

but I have never seen that 'reference' before, so thanks for that.

I am not a programmer so I cant PR or anything like that (this may change in near future :) )

**Comment by Purfview** [comment]
> it also changes the tile to a local one but in English words (like instead of terminator it says 'naboodgar') which is pinglish (an ugly hack between english and persian)

But that's how imdb works and normal title pages show your local title too.
If you are not logged in imdb, because in settings you can select in what language you want to see the titles.

**Comment by mastercho** [comment]
Well in my side even i set to show original title in my account in reference page still shows title according my location, its not showing original title

**Comment by Purfview** [comment]
> 
> 
> Well in my side even i set to show original title in my account in reference page still shows title according my location, its not showing original title

Link to that page?

**Comment by mastercho** [comment]
Her how its displays

https://i.gyazo.com/4526529cf373619194326cd010db4d5f.png

and here hows is my settings

https://i.gyazo.com/09374baa8e2050fbdff1e4272bcd7ce8.png

so using https://www.imdb.com/title/tt0088247/reference  is not good

**Comment by Purfview** [comment]
> 
> 
> Her how its displays

I see, this is some kind of bug as original title is not "Терминатор", anyway, "title display region" should be set to English region, not to Original, so select UK or USA, then the reference pages will work as they should.

Btw, currently new layout title pages has "original/english title" names bug, but not on all pages.

**Comment by Purfview** [comment]
Btw, script finds original title in own ways and expects the front title to be in English.

**Comment by Purfview** [comment]
Btw, I've enabled discussions at https://github.com/Purfview/IMDb-Scout-Mod/discussions
So post there if it's not about script's bug, or if it's bug then open a new issue, let this thread die...

**Comment by rezad1393** [comment]
> Btw, I've enabled discussions at https://github.com/Purfview/IMDb-Scout-Mod/discussions
> So post there if it's not about script's bug, or if it's bug then open a new issue, let this thread die...

I was not familiar with that github feature. I will check it out.
thanks.
