### ISSUE TITLE
Where can I find Custom Quality Profileid?

### ISSUE THREAD

**Issue by garvongithub** [Purfview/IMDb-Scout-Mod#200]
Where do I find this to use my own Quality profiles in sonarr and radarr?

**Comment by Purfview** [comment]
Look at `https://<radarr_url>/radarr/api/v3/qualityprofile?apiKey=<apiKey>` then you want the value from the id field, not the index in the array.

Or `https://<radarr_url>/api/v3/qualityprofile?apiKey=<apiKey>`
