### ISSUE TITLE
"titrari.ro" change the search page. Again.

### ISSUE THREAD

**Issue by stefionesco** [Purfview/IMDb-Scout-Mod#201]
"titrari.ro" change the search page. Again. Maybe you will consider in the next update.

Thanks in advance.

Stef Ionesco

**Comment by Purfview** [comment]
I meant YOU change it!

**Comment by stefionesco** [comment]
I do not change it. I'm not the owner of "titrari.ro". I'm just a user. And now the advanced search page of "titrari.ro" just changes. So I just wanted to let you know.

**Comment by Purfview** [comment]
I meant you change the script with PR here.

Read: https://github.com/Purfview/IMDb-Scout-Mod/discussions/134#discussioncomment-3881338

**Comment by stefionesco** [comment]
Sorry, but I don't get it. Nevermind. I modify myself the script and it's work for me now.

**Comment by Purfview** [comment]
You need to modify it here in GitHub.

**Comment by stefionesco** [comment]
I'm not so handy in this. I try to do it but I'm not sure it was saved.

**Comment by Purfview** [comment]
To do PR is simple: Press on the script in my repo > Press Edit button.
That will create a fork for you automatically, and after your edits GitHub should ask if you want to do PR (Pull request) , then it should be obvious what to press next.

**Comment by stefionesco** [comment]
I think I did something. I hope it will be OK.
I just wanted to let you know and I spend 3 hours to understand what I should do.
Have a nice day.

**Comment by Purfview** [comment]
> I spend 3 hours to understand what I should do

That's just few clicks. 😆

But you didn't clicked to do the Pull request, I see you made a fork and you made a change in your fork.
After you saved change it should have asked you to do pull request. You can do that pull request any time.

**Comment by Purfview** [comment]
Now everyone should get it updated with v20.0.1.

**Comment by stefionesco** [comment]
Thanks for the support.
Next time I will try to do it myself (if I will remember).
