### ISSUE TITLE
Jellyfin skips on chinese

### ISSUE THREAD

**Issue by mastercho** [Purfview/IMDb-Scout-Mod#204]
So when i have Chinese or Korean movie in Jellyfin and their name is in original name at Jellyfin, IMDB Scout doesn't find movie exist in my Jellyfin, reason for this is because when visit `https://www.imdb.com/title/tt7738048/` IMDB i see Original title: `Akjilkyungchal `instead `악질경찰` is there a way to fetch original title and check for it?

Also yavka.net seems updated their search endpoint

**Comment by Purfview** [comment]
> Also yavka.net seems updated their search endpoint

Add PR for it.

> Jellyfin... Akjilkyungchal instead 악질경찰 is there a way to fetch original title and check for it?

No. There always will be various quirks with the title search.
Use a proper media server like `Emby`, there is no such problems.

**Comment by mastercho** [comment]
> Add PR for it.

I have more than 400 sites added to script, would take months to get to yavka and PR

> There is no way. There always will be various quirks with the title search. Use a proper media server like `Emby`, there is no such problems.

Emby is pretty broken, like doesn't loads subtitles, gets wrong info, doesn't make collections etc, Its same script after all with Jellyfin.

You can get the real title like `악질경찰` from api.themoviedb.org

**Comment by Purfview** [comment]
> I have more than 400 sites added to script, would take months to get to yavka and PR.

How "400 sites" prohibiting you to do PR on yavka?

> Emby is pretty broken, like doesn't loads subtitles, gets wrong info, doesn't make collections etc,

Open issue there -> https://github.com/MediaBrowser/Emby/issues
There you can ask for proper search in Jellyfin -> https://github.com/jellyfin/jellyfin/issues

**Comment by mastercho** [comment]
Issues already exists, i open issue here because seems repo is still active, if you retired from project and no more support it you must archive it so someone else can take the ship

**Comment by Purfview** [comment]
Don't open Emby or Jellyfin issues here, if you can grasp this basic common sense then I can retire you from here.

**Comment by mastercho** [comment]
i did open IMDB Scout related issue not `Emby or Jellyfin` related

**Comment by Purfview** [comment]
> i did open IMDB Scout related issue not `Emby or Jellyfin` related

Bye.
