### ISSUE TITLE
Request: Country alternatives for JustWatch

### ISSUE THREAD

**Issue by alcoolfire** [Purfview/IMDb-Scout-Mod#205]
I appreciate the inclusion of JustWatch, but its searchURL is for USA users:
```
https://www.justwatch.com/us/search?q=%search_string%
```
which means that site's Watch Now links are all wrong for non-USA users.

I would like to see JustWatch Canada added, with this searchURL:
```
https://www.justwatch.com/ca/search?q=%search_string%
```
Perhaps in the longer term a more generalized solution might be found to allow users to specify their desired locale and have that be a parameter used in some URLs?

**Comment by Purfview** [comment]
Added `JustWatch (CA)` to v20.1.3.

**Comment by Purfview** [comment]
Yeap, it's typo. Fixed -> https://github.com/Purfview/IMDb-Scout-Mod/commit/5e05f1ad3437bf16646c8e1aac27b835c978634b

**Comment by alcoolfire** [comment]
Thank you :-)
