### ISSUE TITLE
Request: Search icon for libraries using Bibliocommons

### ISSUE THREAD

**Issue by alcoolfire** [Purfview/IMDb-Scout-Mod#208]
Bibliocommons is used by a very large number of library systems, many of which carry a large collection of film/TV content. It would be great if IMDB Scout Mod provided a Bibliocommons search icon, but it would need to be parameterized. For example, these are all valid searches for the same film, but different library systems:

[https://ssfpl.bibliocommons.com/v2/search?query=The%20Marsh%20King%27s%20Daughter&searchType=title](https://ssfpl.bibliocommons.com/v2/search?query=The%20Marsh%20King%27s%20Daughter&searchType=title)
[https://skokielibrary.bibliocommons.com/v2/search?query=The%20Marsh%20King%27s%20Daughter&searchType=title](https://skokielibrary.bibliocommons.com/v2/search?query=The%20Marsh%20King%27s%20Daughter&searchType=title)
[https://epl.bibliocommons.com/v2/search?query=The%20Marsh%20King%27s%20Daughter&searchType=title](https://epl.bibliocommons.com/v2/search?query=The%20Marsh%20King%27s%20Daughter&searchType=title)

A user-specified setting would be needed to set a new URL parameter for an arbitrary local library prefix ("ssfpl", "skokielibrary", or "epl" for the above examples). Just for argument's sake, I'll call the parameter %biblio_prefix%. I might not have this right, but then add a new entry something like the following?

```
  {   'name': 'Bibliocommons Local Library',
      'icon': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAVUExURZVvjVNRo/uiHhCuxtMpkjGDt+psWohgkbwAAAAHdFJOUwP6+fn6Xl5+d1uUAAAAz0lEQVQoz22QvQ6DMAyEr7RhbobuiIG5UsTeATGDEHuEqrz/I/TsOCBBPXD2h38DwIUAtRAmVWdOUfnzFrmXTIJeZNnBornOeNLcsK5BK1cMQ2RNNjjvCYa45LhnrGB0GUyzgQFKJngBNcGHzVbgxpjjSMY8ftYY+LJGzfuX6uMAT9VaVpHjrAI4AP6DS8ml6XnseTFbPaWyuh5Xt7SYj5PzNSYp58ctg84eKKI1093YrKKfEj+NPDJtk4bSuLNbzCPfQSNSFVBrxaHilEyCH52rNvdEVMTYAAAAAElFTkSuQmCC',
      'searchUrl': 'https://%biblio_prefix%.bibliocommons.com/v2/search?query=%search_string_orig%&searchType=title',
      'showByDefault': false},
```

I just used a lossily compressed version of the generic Bibliocommons icon. Ideally there'd be a way to customize those 'name' and 'icon' values according to the specific library's name and logo too, but I guess that would be a much bigger ask.

**Comment by alcoolfire** [comment]
> Just add the library you are using.

Fair enough. I don't fancy advertising my jurisdiction quite that narrowly on a public forum like this, so I'll hold off on doing that for now.

**Comment by Purfview** [comment]
OK, then closing this.
