### ISSUE TITLE
Letterboxd support

### ISSUE THREAD

**Issue by Xazmah** [Purfview/IMDb-Scout-Mod#21]
Most or maybe all movies pages on letterboxd have a link to the movie's imdb page (above the cast) so the tt code can be used from that page to search with the script, there's another script doing the same but it's outdated and doesn't support results checking

https://greasyfork.org/en/scripts/375922-letterboxd-search-bars

**Comment by Purfview** [comment]
Letterbox is already in the script, and it's selected by default. Look at the the icon sites bar just below the title.

**Comment by Purfview** [comment]
Ah you are asking about a script for Letterboxd...
I have no interest in writing such script.
