### ISSUE TITLE
Flickmetrix doesn't work for some titles

### ISSUE THREAD

**Issue by alcoolfire** [Purfview/IMDb-Scout-Mod#212]
The current searchURL for Flickmetrix is not correct, although it may once have been. This is the current searchURL:
```
https://flickmetrix.com/?id=%nott%
```
For whatever reason Flickmetrix is using IMDB IDs for only a subset of their titles. "Pulp Fiction" (1994) is an example where they _do_ use the IMDB ID:

- [https://www.imdb.com/title/tt0110912/](https://www.imdb.com/title/tt0110912/)
- [https://flickmetrix.com/?id=110912](https://flickmetrix.com/?id=110912)

and "Parasite" (2019) is an example where they _don't_:

- [https://www.imdb.com/title/tt6751668/](https://www.imdb.com/title/tt6751668/)
- [https://flickmetrix.com/?id=**4900577**](https://flickmetrix.com/?id=4900577)

If linking by ID isn't possible, is there a URL that allows for search-by-title? I haven't been able to find one, aside from their API that spits out a JSON result.

**Comment by Purfview** [comment]
Ask them there -> https://flickmetrix.com/about

Maybe they can add support for urls like - https://flickmetrix.com/?imdbID=tt6751668

> If linking by ID isn't possible, is there a URL that allows for search-by-title?

I don't see any.
