### ISSUE TITLE
Adding more services

### ISSUE THREAD

**Issue by dimii27** [Purfview/IMDb-Scout-Mod#213]
I spent a couple of hours trying to figure out how to add movie-web on the third search bar.

my solution: 
```
{     'name': 'movie-web',
      'icon': 'https://avatars.githubusercontent.com/u/121455091?s=48&v=4',
      'searchUrl': 'https://mw.lonelil.com/media/tmdb-movie-%tmdbid%',
      'matchRegex': /Not Found/,
      'ignore404': true,
      'inThirdSearchBar': true
},
{     'name': 'movie-web',
      'icon': 'https://avatars.githubusercontent.com/u/121455091?s=48&v=4',
      'searchUrl': 'https://mw.lonelil.com/media/tmdb-tv-%tmdbid%',
      'matchRegex': /Not Found/,
      'ignore404': true,
      'inThirdSearchBar': true,
      'TV': true
},
```

- to change the instance you would simply replace `mw.lonelil.com` with the link of your chosen instance

Then, silly me, I realised there was already an example under 'Custom sites'

It would be nice if you, the user, could add such services without messing with the script's code.

Also being able to expand/minimise categories (Title Page:, Public download sites:, ...) in the script's settings so you can find sites easier without scrolling through the long list of services and settings would be very appreciated

**Comment by Purfview** [comment]
> I spent a couple of hours trying to figure out how to add movie-web on the third search bar.

No need to add it there as the site doesn't return the results, the search results on that site are dynamically loaded and the script can't see them, in your 'movie-web' config those icons are always green.
Place such sites just as a simple icon in `var icon_sites_main =`.
Maybe that site has API to do search?

>to change the instance you would simply replace mw.lonelil.com with the link of your chosen instance

Simply just add a new site if there is a better one.

> It would be nice if the user, could add such services...

Adding a site to the script is just few clicks, read there -> https://github.com/Purfview/IMDb-Scout-Mod/issues/209

> ...without messing with the script's code.

Not sure I understood what that means, you are not "messing" with the actual code, you just add a config for a site.

**Comment by Purfview** [comment]
Added to v20.1.11
