### ISSUE TITLE
Add Simkl.com as external rating site?

### ISSUE THREAD

**Issue by Smoukus** [Purfview/IMDb-Scout-Mod#219]
Hello, your explanation of a PR (https://github.com/Purfview/IMDb-Scout-Mod/issues/209#issue-2146649770) is pointed towards new sites.

However Simkl.com is more like Lettereboxd and Trakt.
I'd like that site added if possible.

I don't mind creating a PR myself if you let me know what should be done differently than above linked issue.

I'm open to any questions.

**Comment by Purfview** [comment]
Dupe of https://github.com/Purfview/IMDb-Scout-Mod/discussions/175

Personally I don't see a point in those ratings, it's like buying another same watch which has lower accuracy...

I don't mind you adding PR with those ratings.

**Comment by Purfview** [comment]
Simkl is already added, you can find it at the icon sites section.
