### ISSUE TITLE
Icons disappearing, has imdb updated its site?

### ISSUE THREAD

**Issue by kaputeko** [Purfview/IMDb-Scout-Mod#224]
It seems that the imdb website has changed and the icons appear and then quickly disappear.

**Comment by Purfview** [comment]
Everything OK on my side, maybe they didn't pushed that update for everyone yet.

**Comment by arogl** [comment]
I tested on 
Firefox 127.0.1 = Works
Chrome 126.0.6478.115 = Icons disappearing
ViolentMonkey = 2.19.0
ImdbScout = 20.2.1

**Comment by Purfview** [comment]
Maybe it's Chrome update to blame? Try older Chrome version.

**Comment by kaputeko** [comment]
Strangely, it's back to normal.
I've done so many things that I don't know what could have solved it.
Thank you for your attention.
