### ISSUE TITLE
'Retroflix-Req' appears to overwrite 'Retroflix' results

### ISSUE THREAD

**Issue by Paladin-z** [Purfview/IMDb-Scout-Mod#226]
Results show Retroflix forum search results ('Retroflix-Req') but not any torrent matches ('Retroflix'). 

Ideally both should show or torrent matches should take priority.

**Comment by Purfview** [comment]
Not sure what you mean, post the imdb link where it does such "overwrite", and post screenshot of such "overwrite".

**Comment by Paladin-z** [comment]
Sorry, both results are now showing and I can't reproduce the issue, obviously a problem my end.
