### ISSUE TITLE
IMDb pages doesn't load on Android

### ISSUE THREAD

**Issue by Sovilor** [Purfview/IMDb-Scout-Mod#227]
Hello,
Tested on Android Firefox nightly, Violentmonkey, Tampermonkey. 

At the moment, only the main page is working (https://m.imdb.com), all subpages doesn't load and this error appears:
(We are unable to load this content at this time. Please refresh the page or try again later.)
Screenshot:
![Screenshot_2024-08-09-16-49-53-899_org mozilla fennec_fdroid](https://github.com/user-attachments/assets/5e0d9045-edda-4514-af22-98605f94ffbf)

Thank you.

**Comment by Purfview** [comment]
I've seen this error on the desktop too, but I don't remember at what circumstances.

I've no idea why this happens, could you for a start try if it works with Firefox Nightly 108.0a1 https://firefox-fenix.en.uptodown.com/android/download/86827784
That was working version the last time I've tested the script on Android.

And the script version at that time was 17.10 https://greasyfork.org/en/scripts/407284-imdb-scout-mod?version=1128932

Btw, do you know at what stable Firefox version they started to allow Tampermonkey?

**Comment by Sovilor** [comment]
Okay i spent 3 hours testing many versions of Firefox nightly and 2 Chromium-based Browsers for Android and all the userscript managers, and the error kept showing and no page loaded, 
then i started to disable the sittings, till it worked.

What is causing the error is this option in the sittings (Remove IMDb ads?).

One more thing i noticed (if it may help):
The script was working fine but suddenly the error started to show up, and that was before the last 2 updates of the script, so the last 2 updates didn't cause the issue and obviously didn't fix it.

To answer your question, the Addons only work on Android Firefox nightly and its forks, and Tampermonkey always worked as i remember.
stable Firefox version doesn't support add-ons yet.

**Comment by Purfview** [comment]
> 2 Chromium-based Browsers for Android

What are those? What about vanilla Chrome?

> stable Firefox version doesn't support add-ons yet.

It support them for a year or two.

> What is causing the error is this option in the sittings (Remove IMDb ads?).

That I can fix, I just wonder what would be universal method to detect the mobile browsers.

> The script was working fine but suddenly the error started to show up, and that was before the last 2 updates of the script, so the last 2 updates didn't cause the issue and obviously didn't fix it.

IMDb site changed some of it's code and now it doesn't like some elements removal, strange that it doesn't affect desktops.

**Comment by Sovilor** [comment]
Kiwi Browser, ungoogled-chromium 88.0.4324.182

**Comment by Purfview** [comment]
> Kiwi Browser, ungoogled-chromium 88.0.4324.182

Check if it's fixed in v21.3. I've tested only Firefox.

**Comment by Sovilor** [comment]
It's fixed, Thank you.
