### ISSUE TITLE
[request] Old layout for cast

### ISSUE THREAD

**Issue by Tellotex** [Purfview/IMDb-Scout-Mod#231]
IMDb now forcefully brings the old layout https://www.imdb.com/name/nmXXXXXXX/fullcredits to the new layout, which is messy and cluttered. 

Would it somehow be possible to make the script force the old fullcredits layout for cast when https://www.imdb.com/name/nmXXXXXXX/ is visited?

**Comment by Purfview** [comment]
> Would it somehow be possible to make the script force the old fullcredits layout for cast when https://www.imdb.com/name/nmXXXXXXX/ is visited?

There is already this option implemented in the script to force "fullcredits".

> IMDb now forcefully brings the old layout https://www.imdb.com/name/nmXXXXXXX/fullcredits to the new layout, which is messy and cluttered.

Nothing I can do if they removed "fullcredits" page, ask them to bring it back there:
https://community-imdb.sprinklr.com/conversations/imdbcom/add-a-contributor-text-view-for-name-credits
