### ISSUE TITLE
How do I get this script to work?

### ISSUE THREAD

**Issue by jackbrannen** [Purfview/IMDb-Scout-Mod#239]
I've installed Userscripts for Safari on my Mac and enabled it in Safari extensions.

But when I press the "Install this script" button [on this page](https://greasyfork.org/en/scripts/407284-imdb-scout-mod), it just loads a .js file in my browser.

What am I missing?

TIA

**Comment by Purfview** [comment]
>What am I missing?

Maybe you don't have a userscripts manager installed. What managed do you use?

Btw, if you will want to use any site where it needs to login then it won't work on Safari because it's blocking cookies.
Use Firefox, the last good internet browser.

**Comment by Purfview** [comment]
>I've installed Userscripts for Safari on my Mac

Oh that "Userscripts" IS manager, first time I hear about it.  😆
For issues of that manager you should ask the creator of that manager: https://github.com/quoid/userscripts/
