### ISSUE TITLE
Radarr, Sonarr API problem

### ISSUE THREAD

**Issue by sllllr** [Purfview/IMDb-Scout-Mod#241]
In recent days I have been having a problem with an API error (Invalid Radarr/Sonarr API key). Nothing has been changed in Radarr and Sonarr with the API key. Other services using their API on these keys work OK.

The problem occurs on Chrome and on Firefox. Previously it was OK all the time.

Script version 23.4.

**Comment by Purfview** [comment]
Do you mean that the problem started after the script update? But nothing changed in the script for Radarr/Sonarr too.

Look at the settings and check if the keys are actually there.

**Comment by sllllr** [comment]
As I mentioned earlier, I did not change anything in the settings. Yes the API keys are in the settings as they were before. It was working before and now there are API errors. I was originally using on Chrome. I did a fresh install on Firefox and there is the same error. The only thing that has changed is that there is an error about the API Key for Radarr and Sonarr. The rest works without a problem.

**Comment by Purfview** [comment]
Try it with another manager like Violentmonkey, try to check logs if something is there - https://wiki.servarr.com/radarr/troubleshooting

**Comment by sllllr** [comment]
I installed Violentmonkey added Radarr data and it's the same :)

**Comment by Purfview** [comment]
Post your Radarr/Sonarr versions.
What logs show?

**Comment by sllllr** [comment]
The latest version of Radarr is already installed
5.14.0.9383
—
26/10/2024


The latest version of Sonarr is already installed
4.0.10.2544
—
26/10/2024

Radarr and Sonarr logs show nothing about API access :(

**Comment by Purfview** [comment]
You say nothing changed but those are the latest Radarr/Sonarr versions, maybe the issue started after you updated Radarr/Sonarr?

**Comment by Purfview** [comment]
Maybe you updated it yesterday/today?
"update is from 26/10/2024" doesn't tell when you actually updated it.

Try older versions of the script: https://greasyfork.org/en/scripts/407284-imdb-scout-mod/versions

**Comment by sllllr** [comment]
It all became clear... Where I have radarr and sonarr is double logging. I had to add radarr and sonarr login data to the URL :) Sorry for the confusion...

**Comment by sllllr** [comment]
That is what is strange. It wasn't needed before :)
