### ISSUE TITLE
firefox update bug?

### ISSUE THREAD

**Issue by rezad1393** [Purfview/IMDb-Scout-Mod#3]
when I change the sites to check for torrent and then save and close it seems that nothing is saved and I still get that last selection.
could this be the new firefox bug?

**Comment by Purfview** [comment]
Did you tried to refresh imdb page?

**Comment by rezad1393** [comment]
> Did you tried to refresh imdb page?

I know you (and others) get a lot of stupid questions and requests from users (a user like me) but please sometimes assume that the user is not always a retard.
I have reported bugg for this script before and I use it so I have known that when I click after save on the done button the page refreshes.
what I reported was for after page refresh.

**Comment by Purfview** [comment]
Installed Firefox v84.0 64bit, installed ViolentMonkey, installed IMDb Scout Mod:
Script works as expected, settings are saved.

**Comment by rezad1393** [comment]
I updated firefox. 
and I used my normal profile so maybe I need to reinstall this script to test.
sorry about my past language.

**Comment by rezad1393** [comment]
weird.
now when I opened an imdb page the setting was changed (from last change I last time that didnt stick)

**Comment by Purfview** [comment]
It works for me normally without any restart. Maybe some "blocking" plugin is to blame, check what is going on in Browser Console ("Ctrl+Shift+J") when you change settings.

**Comment by rezad1393** [comment]
I dont see any weird messages.
only alot of cookie rejects that is normal for firefox and third party cookie.
I may disregard this ubg for now that I have found the workaround.
firefox has some weird bugs, that finding them is really hard.
you can go ahead and close this cause I dont think I can find the issue.

**Comment by Purfview** [comment]
Maybe it is not related to Firefox update but to update of some add-on, try to disable other add-ons.

**Comment by rezad1393** [comment]
I cant reliably test with that because as you can see it not a completely reproducible bug.
but I may try later.

**Comment by rezad1393** [comment]
I think it is a firefox bug (or maybe a weird other addon (maybe violetmonkey) bug that was caused by firefox update)
because today I was trying to create a userscript for a website and whatever I used for the include part in sript the violentmonkey didnt see it. then I disable the scripts globaly in violet monkey (from the flip button in violent monkey icon and and refresh website but the website behaved as if I didnt disable any script.

I think this is not you script fault but can I keep this open to track it here?

**Comment by Purfview** [comment]
I think this has nothing to do with Firefox nor Violentmonkey, both works normally on my side.

**Comment by rezad1393** [comment]
> I think this has nothing to do with Firefox nor Violentmonkey, both works normally on my side.

I understand that.
but as I said it can be some other addon issue.
but how that addon causes the scripts to load when I refresh the page after disabling them from violet monkey is not clear to me.

and as I said restarting firefox "_fixes_" it so you need to use firefox like me. I keep firefox open hours on end and use it sometimes also hours on end. also I use your addon and change its setting almost every week and before this firefox update I didnt notice this, and violet monkey update is way in past so I have to be sure.

I close this here cause I need to fix that issue first before I try this one.
