### ISSUE TITLE
Site with CSRF token?

### ISSUE THREAD

**Issue by mastercho** [Purfview/IMDb-Scout-Mod#39]
I just wonder if you can add website which on post data have CSRF token?

For example forums build with XenForo 

https://forum.dirtywarez.com/search/search

**Comment by Purfview** [comment]
No sure what you are  asking for. Dirtywarez is already included, you can find it t Public download sites>DW

**Comment by mastercho** [comment]
if you type anything in search bar you will see that in POST data sending CSRF token but seems you found another way to do that with GET for DW. 

In that kind of websites which have CSRF token we first need send get parse token then do the post, was asking if you have intention to implement in future this

**Comment by Purfview** [comment]
I dunno any such site. What site you want to be included?

**Comment by mastercho** [comment]
https://www.szenebox.org/
https://dl4all.biz/
https://3dsbs4u.com/index.php?do=search
http://mygully.com/

**Comment by Purfview** [comment]
Added in v9.12.1.
On szenebox I don't see any relevant content for this script to search, if there is then open a new issue.
