### ISSUE TITLE
[question] Custom website order

### ISSUE THREAD

**Issue by dimqua** [Purfview/IMDb-Scout-Mod#4]
Hi,
Is it possible to add a feature to change the order of websites on a search bar without editing the script?
Because, if I understand it correctly, all the custom changes made in the script will be lost once it gets updated.

**Comment by Purfview** [comment]
> 
> 
> Hi,
> Is it possible to add a feature to change the order of websites on a search bar without editing the script?
> Because, if I understand it correctly, all the custom changes made in the script will be lost once it gets updated.

I'm not sure what you meant by adding feature without adding it.

**Comment by dimqua** [comment]
@Purfview I would like to change the order of websites, but in order to do so I have edit the script because by default sites are displayed in alphabetical order which is less convenient IMHO.

**Comment by Purfview** [comment]
There is no display order at all, it's almost random, depends from how fast/slow site responds.

**Comment by dimqua** [comment]
@Purfview well I do not use the search function as I prefer to search manually and in this case sites are displayed as they specified in the script. Isn't it possible to add a config option to specify the order somehow? Because I don't think that editing the script is generally a good idea.

**Comment by Purfview** [comment]
If you use them only as icons then you can edit the sites order in the script, but any change will be overwritten after an update. 
Config option is possible, but I personally not interested in coding it.

**Comment by dimqua** [comment]
@Purfview thanks for the answer anyway. But what's the purpose of custom sites then? If all of them will be overwritten eventually?

**Comment by Purfview** [comment]
So you can easily paste them back.
