### ISSUE TITLE
help with custom site with html 404 code error

### ISSUE THREAD

**Issue by rezad1393** [Purfview/IMDb-Scout-Mod#40]
I am trying to add a website to the custom part.
it is in this format:
https://domain.com/imdb-tt-id/

I use positive match option. and it works with movies that it finds.
the website cant search for imdbid but https://domain.com/imdb-tt-id/ shows the movie that it finds.
but the website returns 404 html code for movies that are not there.
and when it does it puts it in  " logged out: my-domain" 
it there anyway to tell it that 404 html code is actually just a movie not found?

**Comment by Purfview** [comment]
Can you share an actual link to website and entry for it?

**Comment by rezad1393** [comment]
> Can you share an actual link to website and entry for it?

sure
a working movie
https://aramovie.xyz/tt0048570/

a non working movie. which in firefox browser console I see that it gives a 404 error.
https://aramovie.xyz/tt0048571/

**Comment by Purfview** [comment]
Added to v9.13.1
Check if it works ok.

**Comment by rezad1393** [comment]
how did you find the search?
when I use its search it doesnt work with imdb-tt-ids

**Comment by Purfview** [comment]
It works with tt id, just converts it to some Persian yada yada for "GUI". Inspect network with browser's developer tools.

**Comment by rezad1393** [comment]
I know yours work.
I meant when I use its search part in the website I cant search with imd-id. only with text name of movie.

**Comment by Purfview** [comment]
Just paste ID in search without pressing enter, website does autosearch suggestion, that's how I found that.

**Comment by rezad1393** [comment]
oh. :(
