### ISSUE TITLE
Some fresh sites to add

### ISSUE THREAD

**Issue by mastercho** [Purfview/IMDb-Scout-Mod#41]
When you are free you can add these 

https://main.starwarez.to/index.php?search/search
https://www.ddlspot.com/
https://www.apps4all.com/
https://www.magnetdl.com/
https://warez-world.org/
https://www.warezheaven.com/
https://nima4k.org/
http://www.allyoulike.com/
https://filmfans.org/

:)

**Comment by Purfview** [comment]
Added SW and WH to v9.14. 
Imo, other sites are not worth to be bothered with.

**Comment by mastercho** [comment]
their database is way back to 2011 so many content which cant be find in other sites but i understand you being lazy, i would feel same lol

**Comment by Purfview** [comment]
> 
> 
> ...many content which cant be find in other sites...

Which site you meant?

**Comment by mastercho** [comment]
i can give example for http://www.allyoulike.com/87312/duke-2013-dvdrip-ac3/ which i was unable to find anywhere else :)

**Comment by Purfview** [comment]
From the comments there: "links are dead". Same movie I can see on other ddl sites and even 8 uploads on trackers like TPB.

**Comment by mastercho** [comment]
i did add some of them but for example ddlspot doesn't respect escaped characters in regex which is like

   `  'matchRegex': '/has found <strong>0<\/strong> results/',`

any ideas?

**Comment by Purfview** [comment]
No need so long and quotes around regex , try if it works:

   `  'matchRegex': /found <strong>0</,`

**Comment by mastercho** [comment]
I tried but still wont work including on some other hosts i will posts code bellow:

`  {   'name': 'Byte',
      'icon': 'data:image/png;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAAAAMQOAADEDgAAAAAAAAAAAAD+/v7//////////////////////////////////////////////////////////////////////////////////v7+/////////////////////////////Pz8//v7+//8/Pz//v7+//////////////////////////////////7+/v//////////////////////+v///8jO2v+Ulpr/fHx8/42Njf+vr6//5OTk///////////////////////+/v7/////////////+/L//96i///Rf//xzIj/0su7/5qepf9vb3D/bm5t/4CAgP+/v7//+/v7/////////////v7+////////8tr//7xF//+jAP//nAD//6MA//+9OP/56cP/vcDH/3Z2dv9wcHD/cXFx/7y8vP////////////7+/v////j//8JR//+dAP//ogD//6QA//+jAP//ngD//7oz///87v+nqKz/cXFx/3Fxcf9+fn7/6Ojo///////+/v7///PH//+nB///ogD//6QA//+kAP//pAD//6IA//+iAP//4Jv/3uPt/3x8fP9zc3P/cnJy/7y8vP///////v7+///mpP//nQD//6QA//+kAP//pAD//6QA//+kAP//ngD//85v//b9//+Dg4P/c3Nz/29vb/+pqan///////7+/v//6Kr//58A//+kAP//pAD//6QA//+kAP//pAD//54A///Rdf/y+P//goKC/3Nzc/9vb2//rKys///////+/v7///jW//+rEv//oQD//6QA//+kAP//pAD//6IA//+kAv//6rP/0dXe/3l5ef9zc3P/dHR0/8fHx////////v7+////////z3f//54A//+hAP//pAD//6IA//+dAP//yVj/+fj2/5WXmP9xcXH/cHBw/4mJif/y8vL///////7+/v////////v0///Qff//rRr//6AA//+rEf//z2v/6OPU/6GjqP9wcHD/b29v/3t7e//T09P////////////+/v7///////////////////HX//7nwP/h0bL/srOz/32Ahf9qaWn/dXV1/5aWlv/c3Nz//////////////////v7+///////////////////////7////0NTc/6ytr/+enp7/rq6u/8zMzP/4+Pj///////////////////////7+/v/////////////////////////////////////////////////////////////////////////////////+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==',
      'searchUrl': 'https://byte.to/?q=%search_string_orig%&t=1&d1=&d2=&e=1',
      'loggedOutRegex': /Cloudflare|Ray ID|Im not robot/,
      'matchRegex': /Für den Suchbegriff/,
      'both': true},
  {   'name': 'apps4all',
      'icon': 'data:image/png;base64,AAABAAEAEBAAAAEAGABoAwAAFgAAACgAAAAQAAAAIAAAAAEAGAAAAAAAQAMAAAAAAAAAAAAAAAAAAAAAAAD////////////////////////////////////////+/v79/P349fbu5OjfztTLrbn////////////////////////////+/v77+fry7O7k1dvPtb+4kaKib4eSV3KJRmP////////////////+/v79/Pz18PLl19zQtsC5kqSkc4uUWXqLS3aKSnqQVIGdZ4/////////////9/f307vDh0NXLrri0jJ2fa4aPUneKS3+OUoubZpeugarCob7XwNL////+/v76+Pjp3ODSucG8l6SmdoqSVnaJSHSMUIqZYpKugqjGp8Xbx9zu5O/7+Pr+/v759vfl19rPtLy5kaCjcIeRVXWMTXWRV5Khbpq5lLfRuNPm2Oj38/j+/f7////8/Pzs4ePVvcK9mqWoeY2ZY3yRV3WTW4ujcpy9mbrSudPl1+j38vf9/f3////////6+fnl19nNsrq3j52kdIiTWXKKSW2OU4qjcZy/nL3ZxNrs4e77+fv+/v7////////8+/vo3N7RuL+6lKGoeo2WXXSKSm2NUIidaZi5k7bUvNXo2ur49Pn+/v7////////+/v707/DezM/GqLKxhpegboWSV3SPU3+VXpGqfKTBoMDXwtjr4O359/r+/v7////////+/v707+/ezNLHqbOyh5idaIGOUHSMT4aQVY2gbJq5k7fPtdDj0+Tz7fT8/Pz////////+/v75+Pjq3uHUvMO+m6ipepCWXHyMT4GNUI2RV42ib5y1jbLLr8rdytz////////////////+/v749fbq3+PWwMjAnq2rfZOXX4GOUYGLTIWNUYqXX5OicZ/////////////////////////+/v78+/vz7e/j1dnQtsG5k6WkcoyUWXqLSm+HQ2f////////////////////////////////////+/v78+/z28vPq4OTZxczEpLCtgJL////////////////////////////////////////////////////+/v79/P359vcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
      'searchUrl': 'https://www.apps4all.com/app-search.php?q=%search_string_orig%&log=1&x=0&y=0',
      'matchRegex': /has found <strong>1</
  },
  {   'name': 'dllspot',
      'icon': 'data:image/png;base64,AAABAAEAEBAAAAEAGABoAwAAFgAAACgAAAAQAAAAIAAAAAEAGAAAAAAAQAMAAAAAAAAAAAAAAAAAAAAAAAD////////////+/v77+vrr5ePYzMfOvrjQwLre1M/x7ez9/Pz+/v7////////////////+/v79/f3t5+W7pZ2OaVt1SDdtPCptPSt6Tj6XdWnKurT18vD+/v7////////////9/Pze08+Sb2JqOSdlMiBlMiBmNSdoOCxrOS5oNytvRDamjYTt5+X+/v7////9/f3p4+CQa15sOyxqOixqOy1rQDV1RDpxPS9pNSRmMh9rNiRyQzamjYT18vH+/v739vWvlo9rPTNtQDVxRDpxRj94T0t4SUJvQjdpPzZnOy9lMiBqNSNwRDfLurT8/Pzh2deFX1ZwQzl0SEB4TEV6UUyEXFt6T0h1UU9vU0RsTT1mOi5nMiBpOCyXdWnx7evHtrF4TUR3S0N8UUyCWVmEXWGPaW+DXFx9XmKFXk9vUkNqPjZpNCNpOC15TT3e08+3n5t3S0N+VVCGX2GSbHmVcomce5OaeoWNdnp8W2F0T0xsPzNwPC1oOC1uPyzRwbu3o51+Vk2IYF+Sbnujg6C1nsq2oM+8rrGUdIB/Vld3TER4SUF1RDpmNihuPSvPvrnDr6yAWFGNaWuff5G9p8vq4fLh1eyym8yaeJGOaG6EWll1TkpqPTNkMB51RzbYzMfaz82IYVuEXV+WcoS9pMfy6/fn3vGwmMeTb4aDXGB5T0pwRT1qOi1lMh+OaVvr5uL08fCni4eBWFiTb3qxlKq9pse5ocehgZ6OaHaBWFh4TEVvQjhoNyppNyW7pJz7+vn9/f3f1dSSb2yPam2Wcn2XdIaadomTbnqHYGN7UEx0SD9uQDZrOyyTb2Lt5+X+/v7////7+vrQwb+PbWmFXVyFXWCFX2CFXVx/VVB4TkVxRTtrPTKPal7e09D9/Pz////////+/v77+vrf1dSni4WIY1x8Ukt6T0d4TUV2TEKHYFixmZHp4t/9/f3+/v7////////////////9/f308fDaz83Brqq2npi3oZzGtbDh2Nb49vX+/v3///////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
      'searchUrl': 'https://www.ddlspot.com/search/?q=%search_string%&m=1&x=37&y=15',
       'loggedOutRegex': /Cloudflare|Ray ID/,
      'matchRegex': '/found <strong>0</',
      'both': true},

`

Its always shows as found but its not there, how i can see what is returned response as on dev tools network wont catch the requests

**Comment by Purfview** [comment]
`Für den Suchbegriff` is not in the response, check the source code of the page before adding regexp.
You can employ 'positiveMatch' too, check if it works: 
`'matchRegex': />Suche nach/,`
`'positiveMatch': true,`

I didn't checked other sites.

**Comment by mastercho** [comment]
Byte fixed but cant find regex for other 2, seems DOM is loads differently at first and cant find the given regex

**Comment by Purfview** [comment]
From `apps4all` status is 200 and response headers looks normal but response is empty for some reason.

**Comment by mastercho** [comment]
Just to ask for filmfans

```
 {   'name': 'FilmFans',
      'icon': 'data:image/x-icon;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAj3Qf/5h9If+ihiP/rZIl/7edJ//AqCj/xrIp/8m7Kv/Iwyr/xckq/73NKf+00Sf/qtMm/6DVJf8AAAAAj3Qe////////////qY4k/7OaJf///////////8e4Kf/Ivyn///////////+20Cf/rNIm////////////i9Yi/5h+If+ghSL/qY0j/7GXJf+5oif/wawp/8a2Kf/Hvir/xcUq/8HKKf+5zyj/rtIn/6PUJv+X1iT/jNYj/4HXI/+jhyP///////////////////////////////////////////////////////////////////////////932CT/rpIl//////9lNAP/bTwC////////////////////////////lJYC/4uhAv//////////////////////bdkl/7mfKP//////bDwA/3VIAP///////////////////////////5CbAP+EpgD//////////////////////2LaKP/Cqir//////4JTAv+GWwD///////////////////////////+KqAD/e7AA//////////////////////9a2yz/ybUr//////+QZgL/k24A/5d7AP+bhgD/////////////////gLMA/2y3AP9XuQD/PLsA////////////U90x/82+LP//////m3gC/5uAAP+figD/n5UA/////////////////3W7AP9evwD/RsEA/y3BAP///////////0/eN//Nxi3//////6OHAv+fjgD///////////////////////////9mwQD/TcQA//////////////////////9M3z//yswt//////+hkQD/n5kA/5miAP+TrgD/jLUA////////////VcYA/zvIAP8iyAD/CcgA/wDGAP//////SuFH/8PRLP//////n58D/5ykAv+WrgL/i7UC/4C9Av///////////0jJAv8vywL/GMsC/wPLA/8GygX//////0niT/+51Sr///////////////////////////////////////////////////////////////////////////9I41f/r9cp/6jYKP+g2yj/mN0q/47fK/+E4S3/euMw/3LkNP9q5Tn/Y+U//1zlRP9V5Ur/UOVQ/0vkVf9I5Fr/R+Re/6TYJv///////////4zdKf+C3yv///////////9o5Df/YeU8////////////UeVQ/03lVv///////////0XkY/8AAAAAkdom/4nbJ/+A3Sj/eN8r/2/hL/9n4jT/YOQ5/1vkQP9W5Uf/UuVO/0/lVf9M5Vz/SeVh/0flZv8AAAAAgAGsQQAArEEAAKxBAACsQQAArEEAAKxBAACsQQAArEEAAKxBAACsQQAArEEAAKxBAACsQQAArEEAAKxBgAGsQQ==',
      'searchUrl': 'https://filmfans.org/api/v2/search?q=%tt%&ql=EN',
      'loggedOutRegex': /Cloudflare|Ray ID/,
      'matchRegex': /url_id/,
      'positiveMatch': true,
      'both': true}
```


Website query API, and this code works but when i click to found results its opens me API results, how i can redirect it to real website result? Not sure how to use goToUrl in this case
