### ISSUE TITLE
Most important german Trackers

### ISSUE THREAD

**Issue by Hello-olleH** [Purfview/IMDb-Scout-Mod#42]
Hi,
could you please import these Trackers too?

1. https://torrent-syndikat.org --> https://torrent-syndikat.org/browse.php?searchstring=tt9777666&searchtype=name

2. https://tntracker.org --> https://tntracker.org/search/?perPage=75&page=1&onlyup=1&cats=1,2,4,5,6,7,8,10,12,13,14,16,17,18,19,20,22,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46&search=tt9777666

3. https://bittorrentfiles.me --> https://bittorrentfiles.me/browse.php?search=tt9777666&search_where=0&status=0&categos=1&cr=-2&hide=0&orderby=added&sort=desc

4. https://hdcenter.cc --> https://hdcenter.cc/torrents.php?searchstr=tt9777666&freetorrent=&order_by=time&order_way=desc

5. https://tsctracker.org --> https://tsctracker.org/browse.php?c65=1&c107=1&c48=1&c109=1&c22=1&c24=1&c104=1&c38=1&c6=1&c29=1&c130=1&c76=1&c78=1&c75=1&c113=1&c54=1&c5=1&c55=1&c43=1&c20=1&c120=1&c119=1&c121=1&c124=1&c112=1&c128=1&c129=1&c69=1&c72=1&c66=1&c125=1&c68=1&c126=1&c127=1&c133=1&c117=1&c28=1&c42=1&c103=1&c64=1&c37=1&c4=1&c58=1&c116=1&c50=1&search=tt9777666&incldead=0&orderby=added&sort=desc

Regards

**Comment by Purfview** [comment]
Hi, if you can provide access to these sites to purview [at] protonmail.com then I can add them.

**Comment by Hello-olleH** [comment]
The admins won't do that. So I sent you an example link from the search.

**Comment by Purfview** [comment]
> 
> 
> The admins won't do that. So I sent you an example link from the search.

That is not enough to add sites.
