### ISSUE TITLE
support for myduckisdead  and vintageclassix

### ISSUE THREAD

**Issue by rezad1393** [Purfview/IMDb-Scout-Mod#43]
can you add support for these two so i can remove them from my custom sites?

  {   'name': 'my-myduckisdead',
      'searchUrl': 'https://myduckisdead.org/?s=%tt%',
      'matchRegex': /If you want to rephrase your query, here is your chance:/,
      'both': true},
  
  {   'name': 'my-vintageclassix',
      'searchUrl': 'http://www.vintageclassix.com/search?q=%tt%',
      'matchRegex': /No posts matching the query:/,
      'both': true},

**Comment by Purfview** [comment]
Do you pay money for NitroFlare's premium?

**Comment by rezad1393** [comment]
???
no.
I live in iran so I have to use websites that get those file and I download from them.
like
https://www.rapidpars.com

**Comment by Purfview** [comment]
To download from those two sites you basically need to pay for NitroFlare's premium, how do you download from them?

**Comment by rezad1393** [comment]
> To download from those two sites you basically need to pay for NitroFlare's premium, how do you download from them?

as I said I cant buy from them.
those iranian sites buy an account and share it and I pay them.

**Comment by rezad1393** [comment]
these sites usually put their own files that I dont find anywhere else (if there are torrents I dont use these two)
but they have files that others may not have.
but I understand what you mean.
you can close this if you want.
I just wanted to not have to edit the script with every update you release.

**Comment by Purfview** [comment]
No, that site takes files from other sites. Get to better sites if you can't find same material.
For adult stuff I added PornoLab site.

**Comment by rezad1393** [comment]
> No, that site takes files from other sites. Get to better sites if you can't find same material.
> For adult stuff I added PornoLab site.

I have not found a source for many movies in the quality that they release.
I didnt use that one for adult movies (not good for soul) but found it when I wanted a (I think maybe softcore kinda comedy movie) that I didnt find anywhere else.
the duck site releases movies in quality that I cant find in other sites.
for example older movies that where released in xvid (.avi) the duck sites tries to find the dvd and rip in mkv/x264.
trust me I have encounter enough of these cases to have that website added in spite of a lot of movie trackers like KG CG CZ and so on.
but again this is not a bug just a request that you can safely ignore.

**Comment by Purfview** [comment]
When you'll find such "own rip" there then let me know.
