### ISSUE TITLE
pornolad fuzzy search

### ISSUE THREAD

**Issue by rezad1393** [Purfview/IMDb-Scout-Mod#46]
when searching with pornolab and not with ID , the result can be not empty but not the result you want.
like this
https://pornolab.net/forum/tracker.php?f[]=1768&f[]=60&f[]=1111&f[]=508&f[]=555&f[]=1712&f[]=1713&f[]=1775&o=1&s=2&tm=-1&pn=&nm=Au+plus+pr%C3%A8s+du+soleil+2015

it shows on result this:
По вашему запросу ничего не найдено, но возможно вы имели ввиду: soleil
which is:

and show some unrelated results.

maybe add that russian text to match-regex:
По вашему запросу ничего не найдено, но возможно вы имели ввиду:

**Comment by Purfview** [comment]
Fixed in v10.4. Thanks for the report.
