### ISSUE TITLE
ARAMovie is only http

### ISSUE THREAD

**Issue by rezad1393** [Purfview/IMDb-Scout-Mod#47]
ARAMovie is only http, and https is self signed.
edit:
redirected to 
https://aramovie.club/

is you want you can remove this site because this is the cat and mouse game that filtered iranian sites play with the national filtering here: they change their address every time they are filtered.
I will add it to my custom sites.

**Comment by Purfview** [comment]
Works normally with https on my side, maybe that iranian filtering tampers with the site. As long as it works it can be.
