### ISSUE TITLE
some public sites are actaully private?

### ISSUE THREAD

**Issue by rezad1393** [Purfview/IMDb-Scout-Mod#48]
login needed:
https://eliteunitedcrew.org/login.php?returnto=%2Fbrowse.php%3Fsearch%3D%25tt%25%26cat%3D0%26incldead%3D1%26btn%3DSearch

https://mygully.com/search.php?do=process&quicksearch=1&childforums=1&exactname=1&query=%tt%

https://deildu.net/login.php?returnto=%2Fbrowse.php%3Fsearch%3D%25tt%25%26cat%3D0%26Lysing%3D1

https://www.dnoid.pw/account_handler.php?returnpath=%2Ffiles%2F%3Fquery%3D%25tt%25&withq=1

https://forum.dirtywarez.com/search/search?keywords=%tt%

**Comment by Purfview** [comment]
"Login needed" doesn't mean that site is not public. If everyone can login = public.
