### ISSUE TITLE
Custom icon sites

### ISSUE THREAD

**Issue by dimqua** [Purfview/IMDb-Scout-Mod#5]
Could you please add a possibility to add custom icon sites? By adding a specific attribute, for example.

**Comment by Purfview** [comment]
You can add custom icons already by the "icon" attribute.

**Comment by Purfview** [comment]
Ah, you meant the icon sites, add them where all icon sites are. Why you need special attribute for that?

**Comment by dimqua** [comment]
@Purfview to be able to copy-paste them more easily.

**Comment by Purfview** [comment]
How a special attribute is related to that?
You can submit sites to be added.

**Comment by dimqua** [comment]
@Purfview when you add sites to the custom sites section they can only be places to one of searchbars. They can't be added to other icon sites.

**Comment by Purfview** [comment]
Because that place is only for the search sites. Btw, you can fork repository too.
