### ISSUE TITLE
open result page with post paramateres

### ISSUE THREAD

**Issue by rezad1393** [Purfview/IMDb-Scout-Mod#58]
I used the mpost for a website search and it works and if results are found it shows the icon of that website.
how I can use that same for result page when I click on the icon?
is it even possible to open a link in firefox and send post parameters with it from the script icons?

**Comment by Purfview** [comment]
I'm not sure what you meant, share the code for that site.

There is plenty of sites in the script with `mPOST`. Those links work with normal click, but doesn't work with right mouse click, probably it's possible to make them work on right clicks too, need to read on that issue.

**Comment by rezad1393** [comment]
'searchUrl': 'https://the.nextthing.club/imdbsearch.php',
      'mPOST': 'no_imdb_only=0&string=%tt%&year=&genres%5B%5D=0&countries%5B%5D=0&type%5B%5D=0',
it is a register needed forum that I needed to download this movie from
https://www.imdb.com/title/tt10423726/

when I add it to script and click on icon it goes to https://the.nextthing.club

**Comment by Purfview** [comment]
Did you tried other sites with mPOST, like 'DVDCompare' or 'Lumiere'?

**Comment by rezad1393** [comment]
I tried with this
  {   'name': 'T2K',
      'searchUrl': 'https://torrentz2k.xyz/search/',
      'loggedOutRegex': /Ray ID|security check to access|Please turn JavaScript/,
      'matchRegex': /No Results Found/,
      'mPOST': 'q=%search_string%&category=tv&x=0&y=0',
      'TV': true},
and this also doesnt work
it just opens the https://torrentz2k.xyz and not even https://torrentz2k.xyz/search

**Comment by Purfview** [comment]
> dvdcompare also doesnt work.
> does it work for you?

Yes it works. Must be something on your side, create new Firefox profile and try script there (so you can check if it's not some customization issue or interference from other plugin/script).


> you are on firefox or chromium?

Neither. I use Waterfox Classic.

**Comment by rezad1393** [comment]
ok so when you use 'https://torrentz2k.xyz/search/'on say https://www.imdb.com/title/tt4052886/ clicking on its icon takes you where?

**Comment by rezad1393** [comment]
ok so I will investigate it on my side.
thanks a lot.
is there any thing you can think of that I may have done to caused that?

**Comment by Purfview** [comment]
> is there any thing you can think of that I may have done to caused that?

Only that what I mentioned in my second post and that you have javascript disabled (those buttons depends on it).

**Comment by rezad1393** [comment]
I have javascript enabled.
I dont know about the right click part because when I hover over icon it shows the address of website with no result and left clicking on it opens a new tab with the simple website hompage and not the result.

if there any way in firefox to add post parameter to a link at all? maybe if instead of icons you use form (last think I remember from reading about post and html) then it can be done?

but the more important part is why it works for you now and not for me. back to testing.

**Comment by rezad1393** [comment]
ok I created a empty firefox profile and added only the t2k search and used on lucifer imdb page.
but I cant test it because I get error (red around the icon) for t2k.
maybe it has got to do with the website using cloudflare shield.
now I cant test it.

**Comment by Purfview** [comment]
> but if you can add right click too it would be great.

I'll add it to my todo list.

Sometimes websites does POST but they can work with GET too, check if that link works:
https://the.nextthing.club/imdbsearch.php?no_imdb_only=0&string=tt10423726&year=&genres%5B%5D=0&countries%5B%5D=0&type%5B%5D=0

**Comment by rezad1393** [comment]
thank you.
the link didnt work.

**Comment by Purfview** [comment]
Now I remember why it doesn't work, the other `onMouseDown` method works with all mouse clicks, but by browsers it's treated as a popup, so you need to allow popups for imdb site and the right click context menu doesn't work on such icons. 

You don't need to use middle/right click with this script, as all icons opens in a new tab anyway, so I'll leave it as it's now.

**Comment by rezad1393** [comment]
it seems that I didnt mess up.
now the script doesnt open the search results again and opens the homepage again.
weird.
tested with both https://torrentz2k.xyz/ and https://the.nextthing.club

**Comment by Purfview** [comment]
It's on your side, only not a left mouse click or disabled javascript makes it to not work.
Try to turn off blocking addons.

**Comment by Purfview** [comment]
> now the left click doesnt open the search results again and opens the homepage again.
> tested with both https://torrentz2k.xyz/ and https://the.nextthing.club

T2K wasn't working because site's search changed. Updated it in 11.1.
