### ISSUE TITLE
tntracker

### ISSUE THREAD

**Issue by Hello-olleH** [Purfview/IMDb-Scout-Mod#59]
I would like to invite you to https://tntracker.org, so you can make IMDB-Scout für search in this Tracker.

**Comment by Purfview** [comment]
Sure, send it to purfview at protonmail com

**Comment by Hello-olleH** [comment]
done

**Comment by Purfview** [comment]
Search be ID doesn't work for me. Does it work for you?

https://tntracker.org/browse?imdb=7126948
or
https://tntracker.org/search/?perPage=75&page=1&onlyup=1&cats=1,2,4,5,6,7,8,10,12,13,14,16,17,18,19,20,22,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46&search=tt7126948

**Comment by Hello-olleH** [comment]
Search works just with Film/Serial title name.

https://tntracker.org/search/?perPage=75&page=1&onlyup=1&cats=1,2,4,5,6,7,8,10,12,13,14,16,17,18,19,20,22,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46&search=Wonder%20Woman%201984

**Comment by Purfview** [comment]
Added to v10.2.
For search to work the site needs authorization token. Get it with Developer Tools in browser, look at request headers where they have "Authorization:", copy and paste it to the script's settings.

**Comment by Hello-olleH** [comment]
Developer Tools? How in Firefox?

**Comment by Purfview** [comment]
Try "F12" key -> Network
