### ISSUE TITLE
[Request] Add support for local Jackett

### ISSUE THREAD

**Issue by Xazmah** [Purfview/IMDb-Scout-Mod#63]
Most added indexers in Jackett support searching by id, URLs are usually like this

http://localhost:9117/UI/Dashboard#search=tt0055630

**Comment by Purfview** [comment]
What is the point to search same thing twice?

**Comment by Xazmah** [comment]
Maybe added to Icon sites (no search) section, cause I have auto search disabled, I don't want to auto search every title page I visit
