### ISSUE TITLE
Reference view not always forced

### ISSUE THREAD

**Issue by Xazmah** [Purfview/IMDb-Scout-Mod#65]
While having refence view enabled (in the script settings) and visiting a title from

https://www.imdb.com/chart/top/ or https://www.imdb.com/chart/toptv/

The script fail to load the reference mode

But if enabled in https://www.imdb.com/preferences/general it work just fine

**Comment by Purfview** [comment]
Nice catch, fixed with: https://github.com/Purfview/IMDb-Scout-Mod/commit/b6824709a8a1e2867e39ba5de055552dca6a05d6
