### ISSUE TITLE
[Request] Amazon.de

### ISSUE THREAD

**Issue by Hello-olleH** [Purfview/IMDb-Scout-Mod#66]
Hi,

can you please add amazon.de to "Icon sites (no search)" too?
Thanks. 

Regards.

**Comment by Purfview** [comment]
Isn't that what you should set in amazon preferences: https://www.amazon.com/gp/customer-preferences/select-language

**Comment by Hello-olleH** [comment]
Unfortunately, no. 
Amazon Prime in Germany has a different host and contents.

**Comment by Purfview** [comment]
But that amazon.com link is not "amazon prime". I have no idea what this prime stuff is, you will need to submit PR your self.

**Comment by Hello-olleH** [comment]
All right. 
I thought that was like a shortcut for Netflix. Because you have netflix button too. 
Thanks

**Comment by Purfview** [comment]
I've no idea about Netflix too (it's not mine addition).

**Comment by Hello-olleH** [comment]
An example for Amazon.de search for "Jeremy Clarkson": https://www.amazon.de/s?k=jeremy+clarkson&i=instant-video

**Comment by Purfview** [comment]
Added "Amazon Prime (DE)" with https://github.com/Purfview/IMDb-Scout-Mod/commit/6badba98606f2ba3c60a35377f8219cceead9b27

**Comment by Hello-olleH** [comment]
Thank you very much
