### ISSUE TITLE
Radarr integration type parsing error

### ISSUE THREAD

**Issue by chryzsh** [Purfview/IMDb-Scout-Mod#69]
Trying to add a movie with any custom quality profile set in the settings for Radarr leads to an error in the API and the movie not getting added. The regular popup says "undefined" has been added. This applies as long as the "custom" option is selected for quality profile and with any number provided. The error from the Radarr API is the following:
`Radarr.Http.REST.BadRequestException: BadRequest: Invalid request body. The JSON value could not be converted to System.Int32. Path: $.ProfileId`

This appears to be caused by some problem with type parsing and Radarr enforcing a bit stricter type validation than in the past. I found a small workaround that seems to do the trick. Change line 6820 https://github.com/Purfview/IMDb-Scout-Mod/blob/master/IMDb_Scout_Mod.user.js#L6820 to add a parseInt which forces the ID to be sent as an Int and not a string (I presume). 
`movie.ProfileId = parseInt(GM_config.get("radarr_customprofileid"));`

I tested this locally and it seems to do the trick. However, I'm not js proficient or familiar with the details of the code, so this might not be the best solution, but it worked as a workaround.

**Comment by Purfview** [comment]
Thanks for the report. Should be fixed in v13.3, for Sonarr too.
