### ISSUE TITLE
IMDB external ratings not working

### ISSUE THREAD

**Issue by YScorpion** [Purfview/IMDb-Scout-Mod#72]
I don't know if it's a known issue or if i did something wrong, but the imdb external ratings never works.
It shows the rest (metatric, allociné, rotten) but the imdb ones are always grey (-)
Also, the rotten tomatoes ratings don't work with all movies, even if there's an actual rating in rottentomatoes website.
Is there a fix, the top 1000 voters and female are a really good indicator.

**Comment by Purfview** [comment]
They work for me.
Did it worked before and stopped? Post imdb links where RT ratings doesn't work.

**Comment by YScorpion** [comment]
Nope, the imdb ratings never worked for me since you implemented it, i don't know what's the problem with it.

![Capture d’écran 2021-07-24 014605](https://user-images.githubusercontent.com/11796399/126852783-b1bff8d8-8644-492a-840f-6c6160deae4f.png)
![Capture d’écran 2021-07-24 014726](https://user-images.githubusercontent.com/11796399/126852790-f41aed47-9528-43b0-84bd-b838e860a13b.png)
![Capture d’écran 2021-07-24 014521](https://user-images.githubusercontent.com/11796399/126852794-3c4e6f1d-c707-4396-ad50-2539783336a1.png)

**Comment by Purfview** [comment]
RT ratings should be fixed with https://github.com/Purfview/IMDb-Scout-Mod/commit/990105b6bbc0de16a52753f43ed7f2979741fb3c

**Comment by Purfview** [comment]
For IMDb ratings I need more info:

1) Browser's & monkey's versions.
2) Screenshot of the browser's console. For example in Firefox press Ctrt+Shift+J, clear console then refresh imdb page, select only errors, warnings, logs tabs, make a screenshot.
3) Copy of the page source code from https://www.imdb.com/title/tt0088247/ratings could help too.

**Comment by YScorpion** [comment]
1. Chrome Version 92.0.4515.107 (Build officiel) (64 bits) // Tampermonkey 4.13

2. Errors:
![Capture d’écran 2021-07-24 104908](https://user-images.githubusercontent.com/11796399/126865003-d6195503-0fea-43bd-b0ff-dcee60547c95.png)

3. Source code:
[Terminator User ratings source code.txt](https://github.com/Purfview/IMDb-Scout-Mod/files/6872226/Terminator.User.ratings.source.code.txt)

**Comment by Purfview** [comment]
For some reason for you IMDb shows ratings with `,` instead of `.`.
Should be fixed with https://github.com/Purfview/IMDb-Scout-Mod/commit/247259fad933b2301cbe3fd4fe709e33fd0b4212.

**Comment by YScorpion** [comment]
Fixed, thank you, awesome work
![Capture d’écran 2021-07-24 115700](https://user-images.githubusercontent.com/11796399/126866392-15c22943-5e5b-4d39-96a4-7ae45b1450dd.png)

**Comment by Purfview** [comment]
I just noticed from your "The Terminator" screenshot that Metascore's Must-See badge is not working for you.
Try to disable RT ratings and check if the badge will show, if not then copy the source page of this page -> https://www.imdb.com/title/tt0088247/criticreviews

**Comment by YScorpion** [comment]
No it's working,  it just takes a bit longer than the other badges to change into "must see"
![Capture d’écran 2021-07-24 162150](https://user-images.githubusercontent.com/11796399/126873084-7dae0b97-bb43-424e-ace1-d5586dcaddd6.png)

**Comment by Purfview** [comment]
Ah, good then. For me RT's Certified Fresh is slower, and it should be as it's acquired trough two websites.
Metascore and Must-See badge is acquired from IMDb.
Btw, Allocine's ratings can be acquired only for some movies, as Allocines's IDs the script gets from Wikidata, if it's not there then no ratings.

**Comment by YScorpion** [comment]
Noted, thank you for your patience and your outstanding work, it's really appreciated.
