### ISSUE TITLE
Sites with POST doesn't work

### ISSUE THREAD

**Issue by Hello-olleH** [Purfview/IMDb-Scout-Mod#73]
Hello,

immortalseed is not working. 

Regards.

**Comment by Purfview** [comment]
It works for me.

**Comment by Hello-olleH** [comment]
Should I also export a token for Immortalseed?

If I also click the IS icon, it only opens the Immortalseed home page.

**Comment by Purfview** [comment]
No, auth tokens are needed only for Milkie and TNT.

For me it opens the search page: https://immortalseed.me/browse.php?do=search&keywords=tt0088247&search_type=t_genre

**Comment by Purfview** [comment]
Check what it shows with debug.

**Comment by Hello-olleH** [comment]
<img width="1680" alt="Screen Shot 2021-07-28 at 14 48 18" src="https://user-images.githubusercontent.com/45637723/127324812-731397f1-343e-459f-8348-aa31f27a026a.png">

**Comment by Purfview** [comment]
It's in a console tab, not network.

**Comment by Hello-olleH** [comment]
06:48:19.094 Immortuos GET Response Status: 200
 IMDb Scout Mod.user.js:6212:17
06:48:19.094 Immortuos GET Response Headers: cache-control: no-cache, private

cf-cache-status: DYNAMIC

cf-ray: 6763b6d5ce084a6e-FRA

content-security-policy: block-all-mixed-content ; connect-src 'self' https: blob: https://immortuos.life:8443/socket.io/ wss://immortuos.life:8443/socket.io/ https://immortuos.life/ https://hls.immortuos.live/ local.adguard.org ws://local.adguard.org wss://local.adguard.org; font-src 'self' https: data:; form-action 'self'; frame-src 'self' https: data:; img-src 'self' https: local.adguard.org data:; manifest-src 'self'; media-src 'self' https: blob: about: https://sound.immortuos.live:8878/ https://immortuos.life/; script-src 'self' 'unsafe-eval' https://www.gstatic.com/cv/js/sender/v1/cast_sender.js local.adguard.org; style-src 'self' 'unsafe-inline' local.adguard.org; upgrade-insecure-requests ; worker-src https: blob:

content-type: text/html; charset=UTF-8

date: Thu, 29 Jul 2021 04:48:18 GMT

expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"

feature-policy: autoplay 'self'; camera 'self'; encrypted-media 'self'; fullscreen 'self'; geolocation 'self'; microphone 'self'; midi 'self'; payment 'self'; picture-in-picture *; accelerometer 'self'; ambient-light-sensor 'self'; gyroscope 'self'; magnetometer 'self'; sync-xhr *; usb 'self'

nel: {"report_to":"cf-nel","max_age":604800}

referrer-policy: no-referrer, no-referrer

server: cloudflare

strict-transport-security: max-age=15552000

set-cookie: XSRF-TOKEN=eyJpdiI6Ik11Y3pqN3p3T1AwQmFNUG4wTUJsZ2c9PSIsInZhbHVlIjoieWFUYXhGenpjYVpzU1lIWHl4ZnFEOTRFYTVvTVZIWWtjWDRrb2NKeitNdjFya1hEeS9wbzd6N2xLSGFhZFlIVUR5MHJ0dTh5VEFZK2UxR3ZMTGJOT1licmZ2OXNQQTFkYjBiaGxSajR6UmFxV21NOEN4Q1NhUkl0R0ZmTHNaSkIiLCJtYWMiOiI1OTIzYmU0ZWZkODI0MTFhYjMyN2IzMGQwOWJmNDhkZjY4NGI0MDg2M2JiZGU4NjNlYWQxYzA3ZDc3ODdhZmE4In0%3D; expires=Thu, 29-Jul-2021 06:48:18 GMT; Max-Age=7200; path=/; secure; samesite=lax
laravel_session=eyJpdiI6IkRLMHJKVnBFR1ZWNmhoNmJMbk55d3c9PSIsInZhbHVlIjoiakt3N2tTWmNHRHpjZ2I2d01rYzZSeFVGRmFrVFBOMXpsT0hPQjhLWGZwU2llOWlsblpqWkdJbzNjZ3lraXdyV1FwN1pBZWt5R2VVSlJxVy8vZHl1S3d2TVlrdmMzdStyRzQyNGZEbXk0cFUwQ1Z2V0NQUXFqbnlyS0RmNEdmdHgiLCJtYWMiOiIxYWU2ZTY4OTJkNDE4YjYyZTllYWM5ZTA5NzIzMDBmNGY1OGE3NzgyOGYwODI3OWFhNDBmYzQwMGY3OGM1ODU2In0%3D; expires=Thu, 29-Jul-2021 06:48:18 GMT; Max-Age=7200; path=/; secure; httponly; samesite=lax

vary: Accept-Encoding

x-content-type-options: nosniff

x-download-options: noopen

x-firefox-spdy: h2

x-frame-options: sameorigin

x-permitted-cross-domain-policies: none, none

x-robots-tag: none

x-xss-protection: 1; mode=block, 1; mode=block


 IMDb Scout Mod.user.js:6213:17
06:48:19.094 Immortuos GET Response: <div class="table-responsive">
    <div class="text-center">
                                    
                        </div>
    <table class="table table-condensed table-bordered table-striped table-hover">
        <thead>
        <tr>
                            <th></th>
                        <th>Kategorie/Typ</th>
            <th style="white-space: nowrap !important;"><a class="facetedSearch facetedSort" href="https://immortuos.life/filterTorrents?imdb=12306692&sort=name&direction=asc" id="name" trigger="sort" state>Name</a> <i class="fal fa-sort"></i></th>
            <th style="white-space: nowrap !important;"><i class="fal fa-clock"></i> <a class="facetedSearch facetedSort" href="https://immortuos.life/filterTorrents?imdb=12306692&sort=created_at&direction=asc" id="created_at" trigger="sort" state="2">Erstellt am</a> <i class="fal fa-sort"></i></th>
            <th style="white-space: nowrap !important;"><i class="fal fa-file"></i> <a class="facetedSearch facetedSort" href="https://immortuos.life/filterTorrents?imdb=12306692&sort=size&direction=asc" id="size" trigger="sort" state>Grösse</a> <i class="fal fa-sort"></i></th>
            <th style="white-space: nowrap !important;"><i class="fal fa-arrow-circle-up"></i> <a class="facetedSearch facetedSort" href="https://immortuos.life/filterTorrents?imdb=12306692&sort=seeders&direction=asc" id="seeders" trigger="sort" state>S</a> <i class="fal fa-sort"></i></th>
            <th style="white-space: nowrap !important;"><i class="fal fa-arrow-circle-down"></i> <a class="facetedSearch facetedSort" href="https://immortuos.life/filterTorrents?imdb=12306692&sort=leechers&direction=asc" id="leechers" trigger="sort" state>L</a> <i class="fal fa-sort"></i></th>
            <th style="white-space: nowrap !important;"><i class="fal fa-check-square"></i> <a class="facetedSearch facetedSort" href="https://immortuos.life/filterTorrents?imdb=12306692&sort=times_completed&direction=asc" id="times_completed" trigger="sort" state>C</a> <i class="fal fa-sort"></i></th>
        </tr>
        </thead>

        <tbody>
                    </tbody>
        </table>
    <div class="text-center">
                                    
                        </div>
</div>

 IMDb Scout Mod.user.js:6214:17
06:48:20.520 Immortuos-Req GET Response Status: 200
 IMDb Scout Mod.user.js:6212:17
06:48:20.520 Immortuos-Req GET Response Headers: cache-control: no-cache, private

cf-cache-status: DYNAMIC

cf-ray: 6763b6ddbab14a6e-FRA

content-security-policy: block-all-mixed-content ; connect-src 'self' https: blob: https://immortuos.life:8443/socket.io/ wss://immortuos.life:8443/socket.io/ https://immortuos.life/ https://hls.immortuos.live/ local.adguard.org ws://local.adguard.org wss://local.adguard.org; font-src 'self' https: data:; form-action 'self'; frame-src 'self' https: data:; img-src 'self' https: local.adguard.org data:; manifest-src 'self'; media-src 'self' https: blob: about: https://sound.immortuos.live:8878/ https://immortuos.life/; script-src 'self' 'unsafe-eval' https://www.gstatic.com/cv/js/sender/v1/cast_sender.js local.adguard.org; style-src 'self' 'unsafe-inline' local.adguard.org; upgrade-insecure-requests ; worker-src https: blob:

content-type: text/html; charset=UTF-8

date: Thu, 29 Jul 2021 04:48:20 GMT

expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"

feature-policy: autoplay 'self'; camera 'self'; encrypted-media 'self'; fullscreen 'self'; geolocation 'self'; microphone 'self'; midi 'self'; payment 'self'; picture-in-picture *; accelerometer 'self'; ambient-light-sensor 'self'; gyroscope 'self'; magnetometer 'self'; sync-xhr *; usb 'self'

nel: {"report_to":"cf-nel","max_age":604800}

referrer-policy: no-referrer, no-referrer

server: cloudflare

strict-transport-security: max-age=15552000

set-cookie: XSRF-TOKEN=eyJpdiI6ImpjZElXR0M4S1FZWi9EY280aHBudXc9PSIsInZhbHVlIjoiWmhzSjNsc05aYXZ1UmwzUW5SY1FBSWd5K09CcFkwUCtFSFZ4QXdlcFNJWWhxaWMvUDRmU2NqTjFNc25CM0R3RXRWMjNTakdEd0lGR0NBRWRQaUVqNEo1RlZzajk1QXNKNFptcVA3V3ZjUU1rVGp1N0NUN25BR1dzbXg1TVJ4ZjYiLCJtYWMiOiJiMGFmYzMyZDM3ZWE1MTk1NTc4NTcxZjRmM2YxODgyMDU3YmZhMTA0YTg4NjMyYTAwODIzMDBjYzEyYmM3N2ZlIn0%3D; expires=Thu, 29-Jul-2021 06:48:20 GMT; Max-Age=7200; path=/; secure; samesite=lax
laravel_session=eyJpdiI6Iko0RW5sOVFoZGN5dGJqODNybFFkQ3c9PSIsInZhbHVlIjoiWExCZHg4ZGlFeU8vR1ZWWlYxNW53R0V3SHRJNE8ybFdoNHJMZWpVRHU1MFEvWkZIVWJULzFyQ3ROZXpzVVBHd25EcmIvbmRPaldPK25wSVFnSHlBd09PNHRqeldYSU5zakdGeGdIYnpldy9CY2FUamc5TUhZbG91d3VycmFuTmwiLCJtYWMiOiJjZjFmMWNkMzIxMDM4YTk0ZDFhYjVmMjQyNmY2MzcwMDIzNGVlMDlmMmUxNTE5MGExY2QzOThmZmY5ZDU2M2M2In0%3D; expires=Thu, 29-Jul-2021 06:48:20 GMT; Max-Age=7200; path=/; secure; httponly; samesite=lax

vary: Accept-Encoding

x-content-type-options: nosniff

x-download-options: noopen

x-firefox-spdy: h2

x-frame-options: sameorigin

x-permitted-cross-domain-policies: none, none

x-robots-tag: none

x-xss-protection: 1; mode=block, 1; mode=block


 IMDb Scout Mod.user.js:6213:17
06:48:20.521 Immortuos-Req GET Response: <div class="table-responsive">
    <table class="table table-condensed table-striped table-bordered">
        <thead>
        <tr>
            <th class="torrents-icon">Kategorie</th>
            <th>Typ</th>
            <th class="torrents-filename col-sm-6">Request</th>
            <th>Autor</th>
            <th>Votes</th>
            <th>Kommentare</th>
            <th>Belohnung</th>
            <th>Zustand</th>
            <th>Beansprucht / Erfüllt</th>
        </tr>
        </thead>
        <tbody>
                    </tbody>
    </table>
    <div class="text-center">
        
    </div>
</div>

 IMDb Scout Mod.user.js:6214:17

​

**Comment by Hello-olleH** [comment]
There is no error for Immortalseed

**Comment by Hello-olleH** [comment]
![Uploading Screen Shot 2021-07-29 at 06.59.02.png…]()

**Comment by Purfview** [comment]
Looks normal, it's POST link. Probably you are pressing the right mouse button on it, it doesn't work with POST, use the left mouse button.

**Comment by Hello-olleH** [comment]
I do left click. :D
Teamviewer maybe?

**Comment by Purfview** [comment]
Send me teamviewer stuff to purfview at protonmail com

**Comment by Hello-olleH** [comment]
Send, Done

**Comment by Purfview** [comment]
> Send, Done

I didn't got anything, check if you wrote mail correctly.

**Comment by Hello-olleH** [comment]
I find that Problem!
iS Search works from this link: https://www.imdb.com/title/tt9140554/reference
but not from this link: https://www.imdb.com/title/tt9140554

;)

**Comment by Purfview** [comment]
I see, probably redesigned pages stopped using jQuery.
So, what addon was interfering on the reference pages?

**Comment by Hello-olleH** [comment]
None of them! I just disabled all my add.ons and try it without add-on my test. 
I can enable all my addons and use reference IMDB Site.

**Comment by Purfview** [comment]
I don't understand.
Do you mean that you enable all your addons and it works OK on the reference pages?

**Comment by Hello-olleH** [comment]
exactly!

**Comment by Purfview** [comment]
But it didn't work when I was looking yesterday with teamviewer. Or did it work? I'm confused now. :D

**Comment by Hello-olleH** [comment]
I don't remember too. :)) 
But now, when I want to search in iS, then I use reference Page. It's working.

**Comment by Purfview** [comment]
OK. Try again on a reference page with ALL addons enabled . Maybe you deleted some addons yesterday?

**Comment by Hello-olleH** [comment]
Yesterday I deleted one Addon but it was disabled before.

My test now:
With reference  and all enabled Addons ---> iS Search works

**Comment by Purfview** [comment]
But then why I had to disable your addons if it worked?! :)
Anyway, check v13.5, it should it.

**Comment by Hello-olleH** [comment]
Thank you very much :)
