### ISSUE TITLE
ExEv dependency broken, install fails

### ISSUE THREAD

**Issue by koszanski** [Purfview/IMDb-Scout-Mod#74]
![image](https://user-images.githubusercontent.com/48093884/127161513-e3e9c4ac-eea9-4367-8ea5-0ad25f6a91b1.png)
When trying to install the script (tried both Greasemonkey and Violentmonkey), one of the dependencies (ExEv.js) fails to load.
`https://greasyfork.org/scripts/403996-exev/code/ExEv.js?version=808391` is the URL, I assume it's down or something. I assume I can find another mirror of the script and just load it in place as a temporary measure.

Browser is Firefox 90.0.2, using uBlock Origin, Decentraleyes amongst other extensions.

**Comment by koszanski** [comment]
Disabled adblock + Decentraleyes, cleared cookies/site data for greasyfork.org, re-enabled, installed just fine. No idea what that was about.

**Comment by Purfview** [comment]
Sometimes Greasyfork servers are overloaded, after minute or two they start work again.
