### ISSUE TITLE
Load setting

### ISSUE THREAD

**Issue by Hello-olleH** [Purfview/IMDb-Scout-Mod#75]
Is it possible to make "Load setting" button always visible to open setting faster?
<img width="180" alt="Screen Shot 2021-07-29 at 16 23 00" src="https://user-images.githubusercontent.com/45637723/127509293-cab4ea08-6d95-4ec4-96b4-bc36e566d945.png">

**Comment by Purfview** [comment]
Imo, that would be redundant.
