### ISSUE TITLE
(Tracker request) greatposterwall

### ISSUE THREAD

**Issue by Hello-olleH** [Purfview/IMDb-Scout-Mod#78]
Hi, 

there is a new Chinese tracker. Can you please add it to IMDB Scout?
Tracker's Name: Great Poster Wall  
Genre: Movie  
Sign-up Link: https://greatposterwall.com/register.php  

Thank You!

**Comment by Purfview** [comment]
It's closed now, I'll add it when it will open again.

**Comment by Hello-olleH** [comment]
Hi,

I registered an Account! You are welcome to use my account:

https://greatposterwall.com <https://greatposterwall.com/>
jrsdeadD
f.aC-7s!zZmN

Regards

**Comment by Purfview** [comment]
Added to v13.8.3
