### ISSUE TITLE
Episode support for streaming

### ISSUE THREAD

**Issue by Nikralx** [Purfview/IMDb-Scout-Mod#82]
Hello, I am fairly basic when it comes to this kind of programming but I am trying to add Flixtv to the streaming results.
So far I have managed to add movies, but when it comes to TV Series I need to be able to add the Season and Episode number to the URL. 
How would I be able to extract that from IMDB and put them in this URL `/%tmdbid%-<S#>-<E#>`

**Comment by Purfview** [comment]
Do PR of what you made for movies, then when I'll have time I'll look about those episodes.

**Comment by Purfview** [comment]
That FlixTV doesn't have streams ( https://flixtv.club/movie/tt0052077 ).
It just links to another site ( https://fsapi.xyz/movie/tt0052077 ), where I can see only ads...

**Comment by Nikralx** [comment]
Works 100% perfectly for me with adblock. And yeah I know it doesn't have the streams, but it does point me to a page that has 5 sources. 
I am just struggling to get TV Shows to work cause I don't know how to extract the season # and episode # from imdb. If you know how I can do that then I would love to know at least for myself.

**Comment by Purfview** [comment]
> And yeah I know it doesn't have the streams, but it does point me to a page that has 5 sources.

It links to same streams, which are already added, if some not added then let me know.
No need to add bunch of intermediate sites like  flixtv or fsapi who serves only ads.

> I am just struggling to get TV Shows to work cause I don't know how to extract the season # and episode # from imdb. If you know how I can do that then I would love to know at least for myself.

You can't do that. New feature needs to be written to support S01 E01 thingies.
Btw, in your PR you don't search anything there, it's just simple link.

**Comment by Nikralx** [comment]
Okay, thanks well like I said I have no idea what I am doing :P Would be
nice to have TV Episodes available at least but I guess just not possible
now.

**Comment by Purfview** [comment]
Maybe in future I'll try add support for them...

**Comment by Purfview** [comment]
Implemented support for the streaming APIs in v15.0.
