### ISSUE TITLE
world-of-tomorrow.eu

### ISSUE THREAD

**Issue by Hello-olleH** [Purfview/IMDb-Scout-Mod#86]
Clicks on icon of WoT redirected on imdb.com

**Comment by Purfview** [comment]
Lol, why they do that? Is search working?

**Comment by Hello-olleH** [comment]
I don't know. But search is working, if I copy the Link behind the icon. :)

**Comment by Purfview** [comment]
I meant the scripts search, you can see by colors.

**Comment by Hello-olleH** [comment]
Yes, it's green.

**Comment by Purfview** [comment]
That is not indication, it must be green on found and yellow on not found.

**Comment by Hello-olleH** [comment]
it is green on found and yellow on not found. ;)

**Comment by Purfview** [comment]
Check if this works: https://github.com/Purfview/IMDb-Scout-Mod/raw/test/IMDb_Scout_Mod.user.js

**Comment by Hello-olleH** [comment]
Yes! It's works now like TS ;)

**Comment by Purfview** [comment]
Test this cleaner fix: https://github.com/Purfview/IMDb-Scout-Mod/raw/test2/IMDb_Scout_Mod.user.js

I'm interested if TS and TS-Req works with this.

**Comment by Hello-olleH** [comment]
TS icon is green but not working. (Asks for User Pass)

**Comment by Purfview** [comment]
Ok, then the final fix is in v15.1.
