### ISSUE TITLE
https://bluray-disc.de/

### ISSUE THREAD

**Issue by Hello-olleH** [Purfview/IMDb-Scout-Mod#88]
Hi,

can you please add https://bluray-disc.de/ to Other sites/tools (in 2nd bar)? 

Thanks
Regards

**Comment by Purfview** [comment]
Search there for what exactly?

**Comment by Hello-olleH** [comment]
It is like https://www.blu-ray.com for german bluray releases. 

https://www.blu-ray.com/search/?quicksearch=1&quicksearch_country=all&quicksearch_keyword=tt5918982&section=theatrical
https://bluray-disc.de/blu-ray-filme/167445-possessor_2020_4k_unrated_limited_steelbook_edition_4k_uhd_bluray

**Comment by Purfview** [comment]
That I can see my self.
But what exactly to search, what search options to use?

**Comment by Hello-olleH** [comment]
Name of the Film :)

**Comment by Purfview** [comment]
But what search options to select?

**Comment by Purfview** [comment]
Added to v15.2.

As you didn't tell me what to search then I set to: filme, importe, erotikfilme.
