### ISSUE TITLE
No JSON in response for Radarr v4.0.4.5922. Sonarr is working perfectly.

### ISSUE THREAD

**Issue by TalEdd** [Purfview/IMDb-Scout-Mod#89]
![image](https://user-images.githubusercontent.com/63492921/153410293-65a19aa2-7844-4f2c-8f39-ea8654ad4bbd.png)
URL is correct, I copied Sonarr URL to Radarr slot and it doesn't work. Maybe some API changes in Radarr.

**Comment by TalEdd** [comment]
I know I can't use Sonarr URL for Radarr, I meant the URL address is correct, as Sonarr works.
I'll wait for you update  the script to support V4 then. My Radarr automatically updates to latest version, I'm guessing you turned off auto updates.

**Comment by Purfview** [comment]
Should be fixed in v15.2.
