### ISSUE TITLE
TPB returns a LOT of incorrect results

### ISSUE THREAD

**Issue by peppersgc** [Purfview/IMDb-Scout-Mod#91]
Especially with the anti numbers thing they added. This could be fixed by changing %search_string% to %tt% since IMDb ID support is built into TPB. (I really don't want to do a pull request for something as ridiculously simple as this)
Example:
searchUrl': 'https://apibay.org/q.php?q=%tt%&cat=201,202,207,209'
goToUrl': 'https://thepiratebay.org/search.php?q=%tt%&cat=201,202,207,209'

**Comment by Purfview** [comment]
Search will never by accurate on sites where IDs are not mandatory.
For example you wouldn't find this torrent uploaded today if you search by id:
https://thepiratebay.org/description.php?id=56845132

**Comment by peppersgc** [comment]
Yes, but searching by ID did find the torrents with 81 seeds, 22 seeds, etc. It doesn't need to find torrents with 0 seeds that can't be downloaded anyway.

**Comment by Purfview** [comment]
IDs have nothing to do with seeds, torrent can have 1000 seeds and can be not searchable with ID, btw that example I posted is seeded.

I can add separate entry for TPB to search with IDs if you like.

**Comment by peppersgc** [comment]
I don't think I got my idea across. I mean the ID as a way around TPB adding number blocking in search returns. Such as returning 0 results if a release year is included in searches. The seeds I pointed out in reference to very old torrents not being tagged with IMDb ID, and most newer movie and TV ones are tagged.

**Comment by Purfview** [comment]
You are making lots of wild false claims here.

For the last time:
IDs have nothing to do with seeds nor how new/old torrent is. Don't you see example I posted, it's uploaded yesterday...
There is no "number blocking", whatever that means... moreover TPB is not even searched by year...
Btw, you didn't pointed anything tangible.

TPB-ID alternative is added to v15.2.1 if you want get false negatives but no false positives.

**Comment by peppersgc** [comment]
I apologize for this. A TPB mod got back to me, and informed me that the numbers thing was a glitch that lasted less than 3 hours, and only affected TV numbering. Like s01e01, etc. Not years. Regardless, it's fixed now, and this was a waste of my and your time. Again, sorry.
