### ISSUE TITLE
IMDb Scout Mod (Start Error): Element not found! Please report it.

### ISSUE THREAD

**Issue by hasankoroglu** [Purfview/IMDb-Scout-Mod#95]
I think imdb chaned its layout again. TitleBlock__TitleContainer no longer exist anymore.

**Comment by Purfview** [comment]
I'll check what is going on. Thx for report.

Btw, the reference view is still working.

**Comment by Purfview** [comment]
Should be fixed in v16.0.

**Comment by adeep** [comment]
> Should be fixed in v16.0.

Hi, i accidentally clicked pro.imdb link and script show me this error. Maybe you should exclude pro.imdb for this kind of error.
Anyway, thanks for this script 👍 
[https://www.imdb.com/title/tt0098904/](url)
![chrome_5TPhCnWDGD](https://user-images.githubusercontent.com/374042/195612266-5b810ebb-3f9a-4ab2-8ed4-cd91805178dd.png)

**Comment by Purfview** [comment]
> Hi, i accidentally clicked pro.imdb link and script show me this error. 

Excluded pro.imdb in v17.6. Thanks for report.
