### ISSUE TITLE
filmfans.org   and serienfans.org go to homepage instead of movie page

### ISSUE THREAD

**Issue by rezad1393** [Purfview/IMDb-Scout-Mod#97]
filmfans.org   and serienfans.org go to homepage instead of movie page

**Comment by Purfview** [comment]
That's how was added by TheLastZombie: https://github.com/Purfview/IMDb-Scout-Mod/pull/92

Those sites doesn't support going directly to a search result.
Alternative would be going to API's search result: https://filmfans.org/api/v2/search?q=tt1160419
Then you could manually copy url_id "dune_2" and paste into the url -> https://filmfans.org/dune_2

**Comment by rezad1393** [comment]
so adding that need a function added to script?
for extracting the url from answer?
maybe for long term goal of this script?

**Comment by Purfview** [comment]
> so adding that need a function added to script?

No, as you would be doing that manually. :)

**Comment by rezad1393** [comment]
> > so adding that need a function added to script?
> 
> No, as you would be doing that manually. :)

I meant as an extended functionality to this script. right now it doesnt have this function but maybe for later it can be added for particular sites like these.

**Comment by Purfview** [comment]
It's possible to make that happen automatically with additional functions, but I won't bother with that for a few non-important sites.

So, realistic options are the homepage or the api's search result.
